### ISSUE TITLE
Discussion on prediction filenames

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#1006]
## Issue description

This issue aims to open a design discussion about the naming of the prediction files from ivadomed and was brought up in ADS meeting while working on integrating ivadomed's model to ADS.

It concerns the naming of the prediction files in ivadomed with:
- the command `--segment` ([run_segment_command](https://github.com/ivadomed/ivadomed/blob/8fd599a07e4a20e4a4ca8fdc676c31f9a41df438/ivadomed/main.py#L226) in main.py)
- the [pred_to_png](https://github.com/ivadomed/ivadomed/blob/8fd599a07e4a20e4a4ca8fdc676c31f9a41df438/ivadomed/inference.py#L215) function (used to convert NiFTI prediction files to PNG for microscopy)

### Current behavior
Currently, the output file names for the predictions are:
`<original_image_filename>_<target_suffix>_pred.nii.gz`

For example, with `target_suffix = ["seg-manual", "_csfseg-manual"]`, the predictions are named:
`sub-01_T2w_seg-manual_pred.nii.gz`
`sub-01_T2w_csfseg-manual_pred.nii.gz`

This naming is odd as the target suffix often contains the word "manual" as per our [naming convention](https://github.com/ivadomed/ivadomed/wiki/repositories#derivatives) for derivatives, and can be seen as ambiguous (i.e. is it a manual label or an automatic prediction from a model?).

### Expected behavior
I don't have a specific "expected" behavior at the moment, hence the design discussion card.
As far as I know, the `target_suffix` is the only part of the config file that identifies the structures segmented in each class of the model.

Options:
1. Get rid of the "manual" word in the output predictions (ex: `sub-01_T2w_seg_pred.nii.gz` and ex: `sub-01_T2w_csfseg_pred.nii.gz`)
2. Name the predictions with a class number instead of the name of the structure (ex: `sub-01_T2w_class-0_pred.nii.gz`)
3. Others? (please, feel free to add suggestions here)

In ADS and SCT (via the [segment_volume ](https://github.com/ivadomed/ivadomed/blob/8fd599a07e4a20e4a4ca8fdc676c31f9a41df438/ivadomed/inference.py#L321)API):
- In ADS, we chose to follow the ivadomed convention for the moment for consistency (tagging @mathieuboudreau)
- As far as I understand the SCT code, they seem to do the same in sct_deepseg [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/685ab17ff9bebeb38228d52a55b2507b60b52446/spinalcordtoolbox/scripts/sct_deepseg.py#L215) (tagging @joshuacwnewton)

**Comment by dyt811** [comment]
Regarding option 1 and 2, would the prediction contain all classes or typically only a single class? 

I definitely believe if this is not generated by manual labelling, we should not include "manual". Maybe "seg-auto" / "seg-model" just to make it clear for data provenance related reasons, so we can tell how the file is generated? I am not sure if we write anything like that into the nii? Maybe set a rule for "manual" -> "auto/model" translation for the target suffix string substitution so we only generate the right output when manual is provided/trained on?

**Comment by mariehbourget** [comment]
> Regarding option 1 and 2, would the prediction contain all classes or typically only a single class?

Good question! The prediction with `target_suffix` in the name are always single class.
In cases the prediction contains all classes (NiFti files with command `--test`), the "target_suffix" is omitted (as it should), so it is not a problem.

**Comment by jcohenadad** [comment]
How about creating a new field `prediction_suffix` with, in this case, values are: `["seg", "_csfseg"]`

**Comment by uzaymacar** [comment]
I second @jcohenadad’s suggestion.

Automated rules for naming is tricky because they might not always produce meaningful results. For example, in #1031 I proposed to get the first element in the list in the case of multiple raters but as @mariehbourget pointed [here](https://github.com/ivadomed/ivadomed/pull/1031#issuecomment-999896876) this doesn't work well for all scenarios. 

We might have different and more complex `"target_suffix"` scenarios in the future of ivadomed, and a new field `"prediction_suffix"` in the config file would also solve these. To make sure old ivadomed configs stay compatible, we can make this field optional s.t.
* if it is not filled, then `"prediction_suffix"` will just be equivalent to `"target_suffix"` which will reserve the old behavior
* if it is filled, we will use it to generate the prediction filenames

It is also relevant to note that if `"prediction_suffix"` is not filled for the multi-rater case, then as https://github.com/ivadomed/model_seg_ms_mp2rage/issues/27 and #816 points out there will be an error. We can add a meaningful error message like "looks like you have multiple raters, please specify `"prediction"` suffix if this is the case."

Let me know your thoughts! I am happy to open a PR on this once we settle on a solution as this is critical for the https://github.com/ivadomed/model_seg_ms_mp2rage project.

**Comment by mariehbourget** [comment]
> We might have different and more complex `"target_suffix"` scenarios in the future of ivadomed, and a new field `"prediction_suffix"` in the config file would also solve these. To make sure old ivadomed configs stay compatible, we can make this field optional s.t.
> 
> * if it is not filled, then `"prediction_suffix"` will just be equivalent to `"target_suffix"` which will reserve the old behavior
> * if it is filled, we will use it to generate the prediction filenames

Hi @uzaymacar and @jcohenadad,
I'm not sure about adding another `prediction_suffix` field in the config file.

As suggested by Uzay, it would work for our needs and covers potential retrocompatibility issues. However, I think it opens the door to errors/misunderstanding from the users, either not filling the field and defaulting to the old behavior, or not updating the field to correspond to the target suffixes (potential mismatch between prediction and filename).

Moreover, it produces different output filenames depending if the field is present or not in the model (from a programming standpoint, I think it would be easier to deal with consistent filenames (independent from the model/task) for downstream tools, instead of disparate filenames.

My preferred alternative would be to keep the prediction filename agnostic to the model/task by having the files named according to the class (ex: `sub-01_T2w_class-0_pred.nii.gz`).
In my opinion, this is a more robust to different scenarios, lessen the potential for errors with less intervention from the users, and is easier to explain/document for the users.
Note: we are already using the `class0`, `class1`, etc. notation for the columns of the evaluation metrics in `evaluation_3Dmetrics.csv`.

**Comment by jcohenadad** [comment]
Fair points @mariehbourget. I vote for your suggestion (as it solves the _really_ problematic "seg-manual_pred" added suffix), and we'll see how future users react to that. Depending on their reaction we might reopen this issue for discussion

**Comment by uzaymacar** [comment]
Hello @mariehbourget, thanks for your suggestion! I agree, this is much simpler 🙂. I implemented your suggestion in #1043 and added you as a reviewer.
