### ISSUE TITLE
For a trained model, where is the model's native resolution stored?

### ISSUE THREAD

**Issue by mathieuboudreau** [ivadomed/ivadomed#1113]
i.e. the resolution that the input images to be segmented will be resampled to.

I can't seem to find that information in the JSON file of our AxonDeepSeg models (e.g. https://github.com/axondeepseg/default-TEM-model), and the *.pt and *.onnx files are binaries.

Is the information in the JSON and just not "human readable" (resolution isn't mentionned anywhere), not stored there, and/or only in the pt and onnx files?

**Comment by mariehbourget** [comment]
Hi @mathieuboudreau!

The resolution of the model is in the json config file saved with the model [here](https://github.com/axondeepseg/default-TEM-model/blob/8b008eda2a1a03e58c51b4f9a70d9d443d3135e6/model_seg_mouse_axon-myelin_tem/model_seg_mouse_axon-myelin_tem.json#L128):
```
        "Resample": {
            "wspace": 1e-05,
            "hspace": 1e-05
        },
```
Note that the values are in `mm`, ref in doc [here](https://ivadomed.org/configuration_file.html#resample).

**Comment by mathieuboudreau** [comment]
Ah ok, perfect, thanks!

I had a thought that it was 0.01, but of course that's in um for us, so I didn't recognize this block of information as being the correct values. Also I was looking for resolution information, so I must of glanced over "Resample".

Thanks for the quick response!
