### ISSUE TITLE
training/validation/test split

### ISSUE THREAD

**Issue by valosekj** [ivadomed/ivadomed#1206]
Hello! 
I am sorry but based on the [configuration file description](https://ivadomed.org/configuration_file.html#), it is not clear to me how exactly a dataset is split into train-validation-test sub-datasets. There are flags [train_fraction](https://ivadomed.org/configuration_file.html#train-fraction) with a default value `0.6` and [test_fraction](https://ivadomed.org/configuration_file.html#test-fraction) with a default value `0.2`. What about the _validation fraction_? Is it simply 1 - `train_fraction` - `test_fraction` (i.e., 1 - 0.6 - 0.2 = 0.2)? 
Thank you!

**Comment by mariehbourget** [comment]
Hi @valosekj,

> Is it simply 1 - `train_fraction` - `test_fraction` (i.e., 1 - 0.6 - 0.2 = 0.2)?

Yes, that's correct.
If that was not clear from the doc, I can open a PR to add a note regarding the validation fraction as well.

Note that the fractions are applied to the "split_method", so if you have
`"split_method": "participant_id"`
the train fraction of 0.6 will be 60% of the `participant_id` as explained [here](https://ivadomed.org/configuration_file.html#split-method).

Also when lauching the training, you should see this line in the terminal that will give you the exact fractions for each set after splitting:
```
| WARNING  | ivadomed.loader.utils:split_dataset:104 - After splitting: train, validation and test fractions are respectively 0.6, 0.2 and 0.2 of participant_id.
```

**Comment by valosekj** [comment]
Hi @mariehbourget!

> > Is it simply 1 - `train_fraction` - `test_fraction` (i.e., 1 - 0.6 - 0.2 = 0.2)?
> 
> Yes, that's correct. If that was not clear from the doc, I can open a PR to add a note regarding the validation fraction as well.

Yes, It was not clear to me. Thus, an explicit note regarding the validation fraction would be great. Thank you!


> Also when lauching the training, you should see this line in the terminal that will give you the exact fractions for each set after splitting:
> 
> ```
> | WARNING  | ivadomed.loader.utils:split_dataset:104 - After splitting: train, validation and test fractions are respectively 0.6, 0.2 and 0.2 of participant_id.
> ```

Yes, I could see this line. But although I specified `"train_fraction": 0.6` and `"test_fraction": 0.2` in my .json config line, the fractions were a bit different:

```
2022-09-26 11:09:20.231 | WARNING  | ivadomed.loader.utils:split_dataset:100 - After splitting: train, validation and test fractions are respectively 0.579, 0.263 and 0.158 of participant_id.
```

**Comment by mariehbourget** [comment]
> Yes, It was not clear to me. Thus, an explicit note regarding the validation fraction would be great. Thank you!

Ok, I'll let you know when the PR is ready for review.

> Yes, I could see this line. But although I specified `"train_fraction": 0.6` and `"test_fraction": 0.2` in my .json config line, the fractions were a bit different:

That is normal because it depends on the number of `participant_id` available, so the final fractions will be as close as possible to the one you specify in the config file depending of your data.

**Comment by valosekj** [comment]
Great, thank you!
