### ISSUE TITLE
How to know the list of subjects selected in train/validation/test sets?

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1218]
### Motivation for the feature

When training a model, I don't know which subjects were selected (ie: found paired image/label), and those who were discarded from my input BIDS database. 

Also, knowing which ended in the train/validation/testing would be useful. 

How can I retrieve this information? It might be good to document this also (in case not already done).

Cherry on the cake: Having this information available via wandb 😊

**Comment by kanishk16** [comment]
You'd be pleased to know that this is part of the loader v2 that @dyt811 has been prototyping.

**Comment by mariehbourget** [comment]
> You'd be pleased to know that this is part of the loader v2 that @dyt811 has been prototyping.

We also have another issue about this https://github.com/ivadomed/ivadomed/issues/1102, it's been on the radar for a while 😀.

**Comment by jcohenadad** [comment]
Duplicate of https://github.com/ivadomed/ivadomed/issues/1102
