### ISSUE TITLE
Confusion around testing outputs `_pred` and `_pred_painted`

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1229]
### Motivation for the feature

Following the [testing part of the first tutorial](https://ivadomed.org/tutorials/one_class_segmentation_2d_unet.html#evaluate-model), user is asked to load the `_pred` file.

However, when doing this on my dataset (`mp2rage-basel`), this file is empty, whereas the `pred_painted` is not:

![anim](https://user-images.githubusercontent.com/2482071/208456525-029a9a55-33d7-42fc-84b7-1af81046c167.gif)

This raises a few questions/comments:
- how come '_pred' is empty in my case?
- what is the difference between these 2 files?
- do we need to output these 2 files?
- if so, we should document them (a search for `pred_painted` in the ivadomed documentation does not return anything).
- should we recommend in the tutorial to look at the 'painted' version?

**Comment by mariehbourget** [comment]
Great questions! and I agree that the documentation is lacking regarding `pred_painted` files.

> * what is the difference between these 2 files?

`_pred` are the predictions themselves --> these are the files you want to look at for your predictions.
`_pred_painted` are "painted" predictions with 3 different values depending if your "object" is a FP, FN or TP --> for reference, they come from [here](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/evaluation.py#L90) in `evaluation.py`, and the values are described [here](https://github.com/ivadomed/ivadomed/blob/9bb4e7f7bdf72971b3f0559e9dac03d18353f98d/ivadomed/evaluation.py#L14).
They are:
`TP_COLOUR = 1`
`FP_COLOUR = 2`
`FN_COLOUR = 3`

> * how come '_pred' is empty in my case?

I would think that the lesion was not detected my the model. Is the value `3` (for FN) in `pred_painted` by any chance?

> * do we need to output these 2 files?

I don't know about the background story of the painted files but I can see why they would be useful when doing lesions detection.
As a side note, we added a key in the config file to skip object detection when it was not useful (in axon/myelin segmentation for example) in PR #1081. The key is [object_detection_metrics](https://ivadomed.org/configuration_file.html#object-detection-metrics) true or false. If `false`, all "object detection metrics" feature are turned off which are: `painted predictions`, `lesions true positive rate`, `lesions false detection rate` and `Hausdorff score`.

> * if so, we should document them (a search for `pred_painted` in the ivadomed documentation does not return anything).

I agree.

> * should we recommend in the tutorial to look at the 'painted' version?

No, as they are not the predictions but the results (TP, FP, FN) of the detection metrics.

**Comment by jcohenadad** [comment]
Thank you for the thorough response @mariehbourget !

In light of this, I have the following suggestions:
- rename: `_pred_painted` --> `_pred_TruePos1-FalsePos2-FalseNev3`

> I would think that the lesion was not detected my the model. Is the value 3 (for FN) in pred_painted by any chance?

I'll look back, as I had no clue about what _pred_painted was, I had the wrong interpretation, so we can discard some of my questions above. 

> I don't know about the background story of the painted files but I can see why they would be useful when doing lesions detection.

Agreed. As long as this output is well documented.

**Comment by mariehbourget** [comment]
I'm going to cross-ref issue https://github.com/ivadomed/ivadomed/issues/611 here which is highly related.

> In light of this, I have the following suggestions:
> 
> * rename: `_pred_painted` --> `_pred_TruePos1-FalsePos2-FalseNev3`

Thinking about it, the values `[1, 2, 3]` are only true for NIFTI files.
So In the case we convert the NIFTI into PNG for microscopy, the values are then `[85, 170, 255]`.

We are currently not using the "painted" predictions with our microscopy tasks and debated removing them in https://github.com/ivadomed/ivadomed/pull/1185#pullrequestreview-1056047540 but decided to keep them as they could be useful in other tasks in the future.

So we may want to avoid having the "value" in the filename itself, but add it to the documentation instead.
For the filename, I think `_pred_TP-FP-FN` would be sufficient provided we document it properly.
