### ISSUE TITLE
How is `filter_empty_mask` interpreted for 3D kernels?

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1232]
This field:

![image](https://user-images.githubusercontent.com/2482071/208463251-c658ebc9-939f-46b1-ae2a-06d6b8f5ecee.png)

Makes sense for 2D models, but what is a 'slice' in a 3D kernel? If this field is set to `True`, does this imply that the 3D patch is discarded if _at leat_ one slice is empty?

**Comment by mariehbourget** [comment]
> Makes sense for 2D models, but what is a 'slice' in a 3D kernel? If this field is set to `True`, does this imply that the 3D patch is discarded if _at leat_ one slice is empty?

It does not apply to 3D kernels at all.
All [slice_filter_params](https://ivadomed.org/configuration_file.html#slice-filter-params) apply only to 2D slices.

* A **2D slice** is an entire 2D image taken from a 3D volume, ex: an image of size 128x128 taken from a volume of size 128x128x16
* A **2D patch** is a portion of that entire 2D image, ex: a patch of 32x32 taken from a slice of 128x128
* A **3D slice** is a concept that does not exist for our purposes.
* A **3D patch** would be a portion of a volume used for training i.e. a subvolume, ex: a patch of 32x32x16 from a volume of 128x128x16.

There was previously an issue (#1163) and PR (#1164) dedicated to adding the feature to 3D as well, but it seems that changes have not been merged.
Note that in the case of 3D, it would not be a "slice" filter, but a "patch" filter as all training in 3D are done with subvolumes.

We should probably clarify the documentation about the difference between a slice and a patch as well (ref to #1235).
