### ISSUE TITLE
Unclear if `patch_filter_params` also applies to 3D kernels

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1234]
## Issue description

This section of the doc: https://ivadomed.org/configuration_file.html#patch-filter-params

Specifically talks about 2D patches. But does this apply also to 3D patches? If so, doc should be updated. If not, a warning/note should be added for ppl using 3D kernels (so they don't get confused).

**Comment by mariehbourget** [comment]
> But does this apply also to 3D patches? If so, doc should be updated. If not, a warning/note should be added for ppl using 3D kernels (so they don't get confused).

No, all [patch_filter_params](https://ivadomed.org/configuration_file.html#patch-filter-params) apply only to 2D patches, as described in the doc.

Further explanations are available in #1232.
