### ISSUE TITLE
Do not use wandb if not specified in the config file

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#1252]
### Motivation for the feature

My config file does NOT include any wandb field, yet training with ivadomed used wandb:
~~~
2023-01-01 18:25:54.402 | INFO     | ivadomed.loader.loader:load_dataset:118 - Loaded 6958 volumes of shape [32, 32, 16] for the training set.
2023-01-01 18:25:54.402 | INFO     | ivadomed.main:create_path_model:89 - Creating model directory: /home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/model_seg_lesion_mp2rage_20230101_182457-batch_size-8/model_seg_lesion_mp2rage
wandb: Currently logged in as: jcohenadad. Use `wandb login --relogin` to force relogin
2023-01-01 18:25:55.487 | INFO     | ivadomed.utils:initialize_wandb:56 - WandB API Authentication Successful!
wandb: wandb version 0.13.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.6
wandb: Run data is saved locally in /home/GRAMES.POLYMTL.CA/p101317/data_nvme_p101317/model_seg_lesion_mp2rage_20230101_182457-batch_size-8/wandb/run-20230101_182555-3eiodlnq
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run run-1
wandb: ⭐️ View project at https://wandb.ai/jcohenadad/my_project
wandb: 🚀 View run at https://wandb.ai/jcohenadad/my_project/runs/3eiodlnq
~~~

This is probably because the code checks for an environment variable? Anyway, this is highly confusing and undesired. I suggest to not activate wandb if it is not mentioned in the config file.

**Comment by jcohenadad** [comment]
OK, it seems like if wandb was connected in the past on the same server, it reuses the same connection: 

~~~
(ivadomed) p101317@rosenberg:~/data_nvme_p101317$ python                                                                                                                                              Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.login(key='', anonymous='allow', timeout=60)
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
True
~~~

So, this is definitely problematic, and a suggestion would be to 'force relogin'.é

**Comment by jcohenadad** [comment]
Hum... there is no "force relogin" via the API (only CLI). I've tried with the flag `force=True` but it doesn't solve the problem.

Maybe this is related to the presence of:
~~~
(ivadomed) p101317@rosenberg:~/data_nvme_p101317$ cat ~/.netrc
machine api.wandb.ai
  login user
  password xxx
~~~
Source: https://community.wandb.ai/t/wandb-automatically-logeed-into-the-wrong-user-why/2916/10

**Comment by kanishk16** [comment]
This is well documented [here](https://ivadomed.org/configuration_file.html#wandb-api-key) and quoting our documentation:
> Note that once it is successfully authenticated, a message will be printed in the terminal notifying that the API key is stored in the .netrc file in the /home folder. From then on, the value in this key-value pair in the config file could be omitted, like 'wandb_api_key': ''

This may be tricky as in one of its releases, wandb introduced the logging feature without a wandb account (anonymous logging). This is enabled only in the case `wandb.login(key='')` finds an empty string in the argument to the parameter `key` and there's no API key stored in the .netrc file. Unfortunately, there's only one method exposed, and if we want to add this feature we might want to give up on the anonymous logging feature.

**Comment by jcohenadad** [comment]
> This may be tricky

that solves the issue: https://github.com/ivadomed/ivadomed/pull/1253/files
