### ISSUE TITLE
convert_file_to_nifti bug for ADS SEM test data

### ISSUE THREAD

**Issue by mathieuboudreau** [ivadomed/ivadomed#1312]
### Discussed in https://github.com/ivadomed/ivadomed/discussions/1310

<div type='discussions-op-text'>

<sup>Originally posted by **chennyyuee** January 25, 2024</sup>
Dear ivadomed team,

I'm trying to use ivadomed Two-class segmentation to train a model for use in AxonDeepSeg. But when I run ivadomed `-c config_microscopy.json`, using the downloaded tutorial dataset.
I got the following error:
```
  File "C:\Users\ct630\ivadomed_env\lib\site-packages\ivadomed\loader\segmentation_pair.py", line 297, in read_file
    img = self.convert_file_to_nifti(filename, extension, is_gt)
  File "C:\Users\ct630\ivadomed_env\lib\site-packages\ivadomed\loader\segmentation_pair.py", line 360, in convert_file_to_nifti
    _img = np.sum(_img * (.299, .587, .114, 0), axis=-1)
ValueError: operands could not be broadcast together with shapes (744,1154,2) (4,)
```
Is there a way to solve this problem ?

Many thanks!
chenyue
</div>

This user's error is reproducible on my end.

It relates to a part of code that was added (possibly by @kanishk16?) in PR #1297,

https://github.com/ivadomed/ivadomed/blob/4c95d013680ccc3cc1d96a88422e023e6027bcb1/ivadomed/loader/segmentation_pair.py#L352-L360

I ran the debugger using the ADS SEM training data, and found the following for the case where there is an error:

```-> if _img.ndim <= colorspace_idx:  # binary or gray
(Pdb) _img.ndim
2
(Pdb) _img.ndim
2
(Pdb) colorspace_idx
2
(Pdb) props.is_batch
False
(Pdb) _img.shape[colorspace_idx]
*** IndexError: tuple index out of range
(Pdb) _img.shape
(954, 1280)
```

Looking at [imageio's documentation](https://github.com/imageio/imageio/blob/65d79140018bb7c64c0692ea72cb4093e8d632a0/imageio/v2.py#L235-L237), it's not clear what `props.is_batch` is being used for here in relation to setting `colorspace_idx`, @kanishk16 do you recall? The case `is_batch=True` I think would mean it's a list/tuple of images, so what does that have to do with the colorspace?

If I understand the logic, for this image (954, 1280), the image is binary so `_img.ndim <= colorspace_idx:  # binary or gray ` should be triggered but isn't being, because `props.is_batch` is false and then `_img.ndim = colorspace_idx`. So we possibly need a different `colorspace_idx` condition, and/or a different if/else condition.

Lastly, to avoid this in the future, we need to add test images & tests for each cases of this is/else chain, as this issue was missed due to the lack of test coverage of these lines:

<img width="903" alt="Screenshot 2024-01-28 at 9 01 10 PM" src="https://github.com/ivadomed/ivadomed/assets/1421029/ff230e0c-1923-42e9-8f3c-5be9f432873b">

**Comment by mathieuboudreau** [comment]
Playing around I set this,

```
            # make grayscale (treats binary as 1-bit grayscale)
            colorspace_idx = 3
            print(filename)
            if _img.ndim < colorspace_idx:  # binary or gray
                pass  # nothing to do
            elif len(_img.shape)==colorspace_idx:  # RGB
                _img = np.sum(_img * (.299, .587, .114), axis=-1)
            elif len(_img.shape)==colorspace_idx+1: # RGBA
                # discards alpha
                _img = np.sum(_img * (.299, .587, .114, 0), axis=-1)
            else:
                raise Exception("File dimensions exceed 4 (RGBA).")
            if len(_img.shape) < 3:
                _img = np.expand_dims(_img, axis=-1)
```

Which worked fine, up until one file ([data_axondeepseg_sem/sub-rat6/micr/sub-rat6_sample-data15_SEM.png]
(https://github.com/axondeepseg/data_axondeepseg_sem/blob/master/sub-rat6/micr/sub-rat6_sample-data15_SEM.png)), which has a quirk in that it's an a grayscale image but with an alpha channel, meaning it's not covered by one of the above conditions (or the previous ones):

```
  File "/Users/mathieuboudreau/neuropoly/github/ivadomed/ivadomed/loader/segmentation_pair.py", line 359, in convert_file_to_nifti
    _img = np.sum(_img * (.299, .587, .114), axis=-1)
ValueError: operands could not be broadcast together with shapes (744,1154,2) (3,) 
```

So we beed a better way to handle the alpha cases

**Comment by kanishk16** [comment]
I could reproduce the error as well...

> It relates to a part of code that was added (possibly by @kanishk16?) in PR https://github.com/ivadomed/ivadomed/pull/1297 ...

AFAIR, we earlier tried to approach issue #1297 by configuring the plugin followed by conversion into a specific data type -   https://github.com/ivadomed/ivadomed/blob/4c95d013680ccc3cc1d96a88422e023e6027bcb1/ivadomed/loader/segmentation_pair.py#L322-L341
but rather as suggested by the maintainer of `imageio` (ref: https://github.com/ivadomed/ivadomed/pull/1297#discussion_r1267563980), it was better if we delegate the loading to `imageio` and handle conversion as: https://github.com/ivadomed/ivadomed/blob/4c95d013680ccc3cc1d96a88422e023e6027bcb1/ivadomed/loader/segmentation_pair.py#L346-L362
Moreover, this is actually how most of the backend libs handle conversion, as confirmed by @hermancollin (ref: https://github.com/ivadomed/ivadomed/pull/1297#issuecomment-1640849993)

>> The case is_batch=True I think would mean it's a list/tuple of images, so what does that have to do with the colorspace?

As per the [imageio](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.core.v3_plugin_api.ImageProperties.html#imageio.core.v3_plugin_api.ImageProperties) docs:
> is_batch: bool
If True, the first dimension of the ndimage represents a batch dimension along which several images are stacked.

**Comment by mathieuboudreau** [comment]
Is there any case where 

https://github.com/ivadomed/ivadomed/blob/4c95d013680ccc3cc1d96a88422e023e6027bcb1/ivadomed/loader/segmentation_pair.py#L352-L360

would be passed a list of images instead of just an image (per the documentation, it's says `Convert **a**  non-NifTI image into a 'nibabel.nifti1.Nifti1Image' object and save to **a** file.

**Comment by kanishk16** [comment]
@mathieuboudreau Could it be due to that img since we even have a test in place?

**Comment by mathieuboudreau** [comment]
@kanishk16 your tests don't appear to cover this section of the lines though; your tests *load* images, but this is a different function that converts from png to nifti

See the coverage lines missing here:
<img width="903" alt="Screenshot 2024-01-28 at 9 01 10 PM" src="https://github.com/ivadomed/ivadomed/assets/1421029/aa85b789-5182-4b68-a780-12ca1e715946">

Lines 352-360 should be listed there if the tests executed them even once

**Comment by joshuacwnewton** [comment]
(Just a small heads-up: I got the ping on the previous issue, and have been reading through the replies here, and wanted to try my hand at proposing a solution to handle this issue. I hope that's okay!)

**Comment by kanishk16** [comment]
> See the coverage lines **missing** here: ... 
> Lines 352-360 should be listed there if the tests executed them even once

@mathieuboudreau I guess 352-360 shouldn't be there (also they aren't) as they aren't missing bcz being covered by the tests!

**Comment by mathieuboudreau** [comment]
Oh maybe your right, I though the lines indicated the hit lines, not missed lines. My bad! Maybe I had a different setting, but if that's the case, I'm wondering how/why all the tests for each of these cases pass, yet our training dataset fails?

**Comment by mathieuboudreau** [comment]
>ValueError: operands could not be broadcast together with shapes (744,1154,2) (4,)


^from the user's issue; maybe the only problem here is the missing case of greyscale images with an alpha channel, that one if definitely not covered in the current code, and it's an odd edgecase

I'll test it out locally

**Comment by kanishk16** [comment]
@joshuacwnewton feel free to chip in with your suggestions... 

Debugging using the brute force solution:

https://github.com/ivadomed/ivadomed/blob/4c95d013680ccc3cc1d96a88422e023e6027bcb1/ivadomed/loader/segmentation_pair.py#L322-L341

the training works as expected.

Note: Idk how did I miss the typo in the above code... `np.unint8` -> `np.uint8`

**Comment by mathieuboudreau** [comment]
Ok so that seems to be it - reverting to your original code, but adding one `  elif _img.shape[colorspace_idx]==2: #gray with alpha channel` condition,

```
            # make grayscale (treats binary as 1-bit grayscale)
            colorspace_idx = 2 + int(props.is_batch)
            if _img.ndim <= colorspace_idx:  # binary or gray
                pass  # nothing to do
            elif _img.shape[colorspace_idx]==2: #gray with alpha channel
                    _img = _img[:, :, 0]
            elif _img.shape[colorspace_idx] == 3:  # RGB or gray with alpha
                    _img = np.sum(_img * (.299, .587, .114), axis=-1)
            else:  # RGBA
                # discards alpha
                _img = np.sum(_img * (.299, .587, .114, 0), axis=-1)
            if len(_img.shape) < 3:
                _img = np.expand_dims(_img, axis=-1)
```

resolves the issue on my end (training starts). So we just need a PR with that addition, but also adding that image to the test images that run during the CI. @kanishk16 do you agree?

**Comment by kanishk16** [comment]
> Ok so that seems to be it - reverting to your original code, but adding one ` elif _img.shape[colorspace_idx]==2: #gray with alpha channel` condition,
> 
> ```
>             # make grayscale (treats binary as 1-bit grayscale)
>             colorspace_idx = 2 + int(props.is_batch)
>             if _img.ndim <= colorspace_idx:  # binary or gray
>                 pass  # nothing to do
>             elif _img.shape[colorspace_idx]==2: #gray with alpha channel
>                     _img = _img[:, :, 0]
>             elif _img.shape[colorspace_idx] == 3:  # RGB or gray with alpha
>                     _img = np.sum(_img * (.299, .587, .114), axis=-1)
>             else:  # RGBA
>                 # discards alpha
>                 _img = np.sum(_img * (.299, .587, .114, 0), axis=-1)
>             if len(_img.shape) < 3:
>                 _img = np.expand_dims(_img, axis=-1)
> ```
> 
> resolves the issue on my end (training starts). So we just need a PR with that addition, but also adding that image to the test images that run during the CI. @kanishk16 do you agree?

Absolutely 🚀

**Comment by kanishk16** [comment]
> > @joshuacwnewton feel free to chip in with your suggestions...
> > Debugging using the brute force solution:
> > https://github.com/ivadomed/ivadomed/blob/4c95d013680ccc3cc1d96a88422e023e6027bcb1/ivadomed/loader/segmentation_pair.py#L322-L341
> > 
> > the training works as expected.
> > Note: Idk how did I miss the typo in the above code... `np.unint8` -> `np.uint8`
> 
> I don't fully understand - what change did you make to get it running with image https://github.com/axondeepseg/data_axondeepseg_sem/blob/master/sub-rat6/micr/sub-rat6_sample-data15_SEM.png ?

Since this block was inside `except` just raised an error in the `try` to execute this block of code to remove my doubt regarding any potential issue with the img 😅
