### ISSUE TITLE
Add docstrings to all methods

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#250]
Currently, several docstrings are missing. Now that we've implemented a semi-automated API documentation, all docstrings need to be filled.

**Comment by charleygros** [comment]
We started a discussion about the docstring style here: [i156](https://github.com/neuropoly/ivado-medical-imaging/issues/156).
But I do not think that a decision has been taken.
Also reflected in the repo', as the two formats are present:
- [example of Napoleon](https://github.com/neuropoly/ivado-medical-imaging/blob/47957a0e2bd4bef8ad21db70b961347fe812dd9a/ivadomed/postprocessing.py#L46)
- [example of Sphinx](https://github.com/neuropoly/ivado-medical-imaging/blob/master/ivadomed/losses.py#L7)

Note: I think only Sphinx docstring have been imported in the [ReadTheDoc](https://ivado-medical-imaging.readthedocs.io/en/jca-doc/api_ref.html#) for now.

(I have a preference for Napoleon's clarity.)

**Comment by charleygros** [comment]
Suggestion of split:

@andreanne-lemay 
- loader folder
- models

@olix86 
- testing folder
- losses
- metrics

@charleygros 
- main (and derivatives in coming PR #230 )
- transforms
- utils

Does it sound fair?
Happy to discuss this, we could swap etc.

**Comment by charleygros** [comment]
> Note: I think only Sphinx docstring have been imported in the [ReadTheDoc](https://ivado-medical-imaging.readthedocs.io/en/jca-doc/api_ref.html#) for now.

Fixed in #258

**Comment by andreanne-lemay** [comment]
> Suggestion of split:
> 
> @andreanne-lemay
> 
> * loader folder
> * models
> 
> @olix86
> 
> * testing folder
> * losses
> * metrics
> 
> @charleygros
> 
> * main (and derivatives in coming PR #230 )
> * transforms
> * utils
> 
> Does it sound fair?
> Happy to discuss this, we could swap etc.

Seems good to me :)
