### ISSUE TITLE
Add link to (small) toy dataset for tutorial

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#253]
Currently, the tutorial points to a 8GB dataset, which is too big. It would be nicer to point to a smaller data for our tutorials.

**Comment by jcohenadad** [comment]
A viable solution would be to host the toy data under a new organization/repository. Example:
- `ivadomed-data/spinalcord-axial`
- `ivadomed-data/spinalcord-sagittal`

**Comment by Drulex** [comment]
> A viable solution would be to host the toy data under a new organization/repository. Example:
> 
>     * `ivadomed-data/spinalcord-axial`
> 
>     * `ivadomed-data/spinalcord-sagittal`
> 
> 
> @Drulex do you think this is a viable solution?

Sure, I think Github is a good option.

How large are the datasets? Are we going to run in the same file size/push limitations as `spinalcordtoolbox`?

In my opinion the simplest path is to use something like `Github` with a large file extension such as `git-lfs`, `git-annex` or similar.

The most flexible path is to host the data internally, then we can do whatever we want, but we would have to manage the system and maintain it (more complex).

Another option is to host the datasets using a file server service (e.g. Dropbox). In that case we need to implement some business logic to manage access to the data.

**Comment by Drulex** [comment]
I think this is more of a political decision then a technical one. All potential solutions listed above are technologically viable and can scale if needed (unless there are some special requirements I am not aware of). 

Personally I like the `Github` + `git-annex` option.

**Comment by jcohenadad** [comment]
> How large are the datasets? Are we going to run in the same file size/push limitations as spinalcordtoolbox?

in this case we don't have that problem because the whole dataset is 200-400MB, but each file is not higher than ~30MB, so github will do.

**Comment by jcohenadad** [comment]
related to https://github.com/neuropoly/ivadomed/issues/269
