### ISSUE TITLE
Small dataset for tutorials

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#288]
### Aim
Get a small dataset that we could use for tutorials, including training, inference, performance evaluation etc.

### Issues
A dataset that could be used to cover all the main features of the repo'.

### Suggestion:
- Source in SpineGeneric dataset: multi center, open source, SC segmentation and Disk levels already generated
    - Inconvenient: very large dataset. Solution: remove diffusion data + one subject per center
- Multi contrast --> demonstrate FiLM, MultiLabel segmentation, HeMIS
    - Inconvenient: different size. Potential Solution: use data after registration on the MT data.
        - Inconvenient of the potential solution: by doing so, we lose the brain area or sagittal view for disc detection. Potential solution BIS: one small dataset with multi-contrast data (all contrasts reg on MT) + one small dataset with T2 only: `multi_contrast_dataset` and `mono_contrast_dataset`.

### Features to illustrate
Here below the list of features we would like to illustrate. I "ticked" the features that could be illustrated with the above suggestion, if not: I tried to suggest a potential avenue to make it happen.

- [x] FiLMedUnet
- [x] HeMIS
- [x] Adaptative loader
- [x] 2D models
- [x] 3D models
- [x] Mono channel
- [x] Multi channel
- [ ] Multi target: only SC segmentation for now. Potential Avenue: + CSF? +GM on T2star?
- [x] BIDS
- [x] Transfer learning
- [x] Cascade approach
- [x] Segmentation
- [x] BoundingBox Localisation
- [ ] Slice-wise classification. Potential Avenue: Train a model to classify: slice with SC vs slice without SC on T1 or T2 data that include brain area, easily done with the SC mask we have.
- [x] Object detection, eg discs or PMJ
- [x] Training scheme: eg tune Loss, Learning Rate scheduler, transformations etc.
- [x] Evaluation scheme: choice of metrics, uncertainty

**Comment by jcohenadad** [comment]
> one small dataset with multi-contrast data (all contrasts reg on MT)

sounds good 👍  so, that would be the processed spine-generic data, right? 

> + one small dataset with T2 only: multi_contrast_dataset and mono_contrast_dataset.

i would suggest multi_contrast

**Comment by charleygros** [comment]
@jcohenadad : Yes!
So the processed spineGeneric data + (T1, T2) not processed.
