### ISSUE TITLE
Create a microscopy dataset using BIDS

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#302]
Create a small dataset that will be used for testing during the development of the project
(following the creation of BIDS for histology (https://github.com/neuropoly/ivadomed/issues/301))

**Comment by mariehbourget** [comment]
For the example dataset, we'll use the ADS SEM_dataset version 2 (data1, data5, data9, data10, data11, data12, data14, Maxo3_img60 and V9_15) + the testing image of the default_SEM_model version 5 (data15) in PNG format.

Based on ADS paper and the Readme of the dataset, it seems that data 9, 10 and 11 are from the same subject. All others seem to be from different subjects. I think the best would be to assign new subject-labels (rat1, rat2, rat3, etc) and use the current name (“data1”, “V9-15”, etc) as the sample-label (and replacing underscore with dash to comply with BIDS naming).

The masks on ADS dataset have 3 classes (0=background, 127=myelin, 255=axons). They are derivatives and their suffix should be `_seg-axonmyelin-manual`. For the purpose of integrating microscopy data in ivadomed, we should use 2 different masks, 1 for axon (255=axon, everything else is 0) and 1 for myelin (255=myelin, everything else is 0) with suffixes `_seg-axon-manual` and `_seg-myelin-manual` respectively.

The  dataset will be uploaded to the ivadomed repo [here](https://github.com/ivadomed/data_microscopy_SEM_example) and should be renamed `data_example_microscopy_sem`.

When it's done, we should update the link in the BEP, add a version number to the changelog of the BEP and refer to it in the description of the dataset.

**Comment by mariehbourget** [comment]
First version of the example dataset in PNG format is released [here](https://github.com/ivadomed/data_example_microscopy_sem/tree/r20201008) (r20201008)

**Comment by charleygros** [comment]
> The masks on ADS dataset have 3 classes (0=background, 127=myelin, 255=axons). They are derivatives and their suffix should be `_seg-axonmyelin-manual`. For the purpose of integrating microscopy data in ivadomed, we should use 2 different masks, 1 for axon (255=axon, everything else is 0) and 1 for myelin (255=myelin, everything else is 0) with suffixes `_seg-axon-manual` and `_seg-myelin-manual` respectively.

Sounds great to me!

**Comment by mariehbourget** [comment]
Update:
Some changes will be required in the example dataset to follow the development of BEP031. This [issue](https://github.com/ivadomed/data_example_microscopy_sem/issues/3) on the `data_example_microscopy_sem` repo describes the changes as of 20210504.

Of note: the `PixelSize` metadata is no longer a scalar but a 2-numbers (or 3-numbers) array to deal with anisotropic pixel sizes. The current microscopy loader supports both behavior as [commented](https://github.com/ivadomed/ivadomed/blob/5579c71e8c93dfdb0ca72952bdde604b84bc645e/ivadomed/loader/loader.py#L515) in the code.

**Comment by mariehbourget** [comment]
Update of the dataset is in-progress in PR [4](https://github.com/ivadomed/data_example_microscopy_sem/pull/4) on the `data_example_microscopy_sem` repo.

This example dataset will become the "official" SEM dataset for AxonDeepSeg. Names of the `sub-id` may change following a research on the provenance of the files.

**Comment by mariehbourget** [comment]
New release of the example dataset, which is now also the official SEM dataset for `axondeepseg`: [r20210715](https://github.com/axondeepseg/data_axondeepseg_sem/releases/tag/r20210715)
Note: the repo was transfered to the `axondeepseg` organization and renamed `data_axondeepseg_sem`.

**Comment by mariehbourget** [comment]
Update:
After a few "intermediate" versions, the release [r20211130](https://github.com/axondeepseg/data_axondeepseg_sem/releases/tag/r20211130) of the SEM dataset is now up-to-date with the soon to be released microscopy BEP031 in BIDS 1.7.0.
The dataset is also now updated automatically on [Zenodo](https://zenodo.org/record/5498378) with each new release on GitHub.

**Comment by mariehbourget** [comment]
Update:
The Microscopy BEP031 was integrated in BIDS and release officially with BIDS 1.7.0.
All of our microscopy datasets have been updated to version 1.7.0 in https://github.com/neuropoly/axondeepseg/issues/603, as well as the ivadomed testing dataset in https://github.com/ivadomed/data-testing/pull/17, so I'm closing this issue.
