### ISSUE TITLE
Unpleasing display of docstring's attributes in RTD

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#315]
Attributes appear with the same font and size as methods which is not aesthetic (See images in the comment:  https://github.com/ivadomed/ivadomed/pull/313#pullrequestreview-435850180).

Adding a custom css should solve this problem.

**Comment by andreanne-lemay** [comment]
This is a known "issue" https://github.com/sphinx-doc/sphinx/issues/2115. One way to improve the display is to add the line `napoleon_use_ivar = True` in the conf.py file. The header is Variables instead of Attributes : 
![image](https://user-images.githubusercontent.com/49137243/85443536-5de48780-b55f-11ea-965e-d5850356ca05.png)

It is still much better than the previous display. Someone commented this to resolve the Variable to Attibrutes issue: https://michaelgoerz.net/notes/extending-sphinx-napoleon-docstring-sections.html

But this requires forking the Napoleon extension code.

**Comment by jcohenadad** [comment]
> But this requires forking the Napoleon extension code.

the author also mentions "Instead, we may patch it at runtime to achieve the desired behavior. Adding the following code in doc.py will achieve this", would that be a better alternative?

**Comment by andreanne-lemay** [comment]
> 
> the author also mentions "Instead, we may patch it at runtime to achieve the desired behavior. Adding the following code in doc.py will achieve this", would that be a better alternative?

:tada: 
![image](https://user-images.githubusercontent.com/49137243/85449604-f3831580-b565-11ea-9857-59dc353bcbaa.png)

**Comment by dyt811** [comment]
Check with @andreanne-lemay, apparently this has been fixed a while back already. Everything looks pretty on IvadoMed.org anyway.  🍰
