### ISSUE TITLE
RTD/Sphinx: first argument of class is missing

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#318]
Code (notice the `ifolder`):
https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/extract_small_dataset.py#L44

Rendered doc (`ifolder` missing):
![image](https://user-images.githubusercontent.com/2482071/85641577-f7de2a00-b65c-11ea-9e79-fd68b2c1df85.png)

This might be due to the automatic removal of the 1st argument for classes (which typically have the 'self' argument)

**Comment by lrouhier** [comment]
Using `.. autofunction::` in scripts.rst solves the problem but it's not as pretty
![image](https://user-images.githubusercontent.com/22171999/85883502-194f2b00-b7af-11ea-9451-eb7a01d1120a.png)

**Comment by jcohenadad** [comment]
thanks for looking @lrouhier . Not as pretty indeed. Wondering if there is a cleaner alternative... 🤔

**Comment by lrouhier** [comment]
Using `add_module_name=False` in conf.y results in this: 
![image](https://user-images.githubusercontent.com/22171999/85889314-3ab51480-b7b9-11ea-9dc0-7bdfc38c52cc.png)

It is cleaner (maybe less explicit)

**Comment by jcohenadad** [comment]
@lrouhier great, thanks.

a few things:
- if possible, we should not display "prepare_dataset_vertebral_labeling", but only show the function called by `__main__`
- we should add those scripts in the setup.py as scripts entry points

**Comment by lrouhier** [comment]
Do you mean something like this? 
![image](https://user-images.githubusercontent.com/22171999/85897700-db5f0080-b7c8-11ea-8a64-a009d2b1b2a8.png)

**Comment by charleygros** [comment]
@lrouhier : I like the last design a lot, like a lot!
