### ISSUE TITLE
Naming convention for models

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#322]
Init debate: [this comment](https://github.com/neuropoly/spinalcordtoolbox/pull/2748#discussion_r445873840).

**Comment by jcohenadad** [comment]
My suggestion would be:
~~~
task_(animal)_region_(contrast)
~~~
with:
~~~
task = {seg, label, find}
animal = {human, dog, cat, rat, mouse, ...}
region = {sc, gm, csf, brainstem, ...}
contrast = {t1, t2, t2star, dwi, ...}
~~~
we should also probably keep that documented somewhere (hard-coded in the rst? or in a py?)

**Comment by charleygros** [comment]
I would agree for the naming convention!

Regarding where to document this.. few thoughts:
- at the moment, during and at the end of the training, the models are saved under the "[log_directory](https://ivadomed.org/en/latest/configuration_file.html#log-directory)", `log_directory/best_model.pt` and `log_directory/final_model.pt`. The config_file (ie the model metadata) are also saved in this repository, `config_file.json`. The models are then manually renamed when packaging before shipping to OSF etc.
- We could adopt this naming for the log_directory itself or.. create a new entry in the config file, eg model_name, which would follow the naming convention, in order to automatically prepare the model folder as required by our OSF organisation. We would just need to zip it before shipping it. So something like: if log_directory="20200626_experiment685" and model_name="seg_csf_t2", we would have:
```
20200626_experiment685/
    seg_csf_t2/
        seg_csf_t2.pt
        seg_csf_t2.json
```

**Comment by charleygros** [comment]
Something else to talk about: what about multi class model?
Would we have `seg_csf-sc_t2`?

**Comment by jcohenadad** [comment]
> Something else to talk about: what about multi class model?
> Would we have `seg_csf-sc_t2`?

hum, i really don't like mixing "-" and "_". On the other hand, this is what BIDS does, but using the key-value approach, e.g.:
~~~
task-seg_region-csf-sc_contrast-t2
~~~
of course we would end up with horribly-long file names 😬 .

so maybe `seg_csf_sct_t2` would be a good compromise (for now)?

**Comment by jcohenadad** [comment]
>  create a new entry in the config file, eg model_name, which would follow the naming convention, in order to automatically / directly prepare the model folder as required by our OSF organisation. 

i like that!  difficult for me to anticipate all the possible cons though... so i hope the team can brainstorm and give a consensus 👍  if this is the way to go.

**Comment by charleygros** [comment]
> so maybe `seg_csf_sc_t2` would be a good compromise (for now)?

I am happy with this too.

> i like that! difficult for me to anticipate all the possible cons though... so i hope the team can brainstorm and give a consensus +1 if this is the way to go.

I don't think it would be much changes, just few lines of wiring.
The only hesitation I have is the difference between `final_model.pt` (ie model at the last epoch) vs `best_model.pt` (model of the epoch that reached the highest score on the validation set) --> there is pros and cons to both. I personally like to decide on a case-by-case by looking at my training curves.
So the question would be: which one of `final_model.pt` vs `best_model.pt`do we put by default in the `model_name` folder? I would tend towards `best_model.pt` by default. But open to discussion.

**Comment by jcohenadad** [comment]
`final_model.pt` seems more accurate (i.e. it is indeed the final, not necessarily the best)
