### ISSUE TITLE
duplicated changelog

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#326]
https://github.com/ivadomed/ivadomed/releases/tag/v2.0.2 and https://github.com/ivadomed/ivadomed/releases/tag/v2.0.1 (and 2.0.0) have duplicated entries, which makes it extremely confusing to know when the new feature was introduced.

new features/fixes should only be listed once, for one release.

if there is a problem when creating a new release (e.g. missing tag, problem on pypi, etc.), we should either delete the release/tag (i don't support this) or keep the problematic tag, but not duplicate the content. On the new release (e.g. 2.0.2), just mention something like: created new release because problem XYZ with 2.0.1. 

this further motivates the implementation of #262

**Comment by jcohenadad** [comment]
@andreanne-lemay for now, could you please manually remove those duplications in the release changelog? thanks! 🙏

**Comment by andreanne-lemay** [comment]
Should be good now!
