### ISSUE TITLE
Drop Down menu for scripts

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#340]
Scripts does not have a 'drop down' menu in the index of the documentation which is not really convenient.

**Comment by lrouhier** [comment]
Not sure but I think it is due to the fact that there are no titles.

**Comment by lrouhier** [comment]
An option is to create invisible title and to link them in the title. The presentation does change a bit (white sale between the function as seen here: 
![image](https://user-images.githubusercontent.com/22171999/87056232-57971200-c1d3-11ea-892e-5f629c58c552.png)

**Comment by jcohenadad** [comment]
why make them invisible?

**Comment by lrouhier** [comment]
I removed them in the previous PR (after discussion [here](https://github.com/ivadomed/ivadomed/issues/318)). I was trying to maintain the same design

**Comment by jcohenadad** [comment]
i think there is some misunderstanding here. 

AFAIU, this discussion thread https://github.com/ivadomed/ivadomed/issues/318 deals with:
- missing first param
- displaying of parent modules

in https://github.com/ivadomed/ivadomed/issues/340#issuecomment-656179878, you mention about a "title". So I'm confused about what you are referring to exactly.

could you please elaborate with very specific and precise terms.

**Comment by lrouhier** [comment]
I was referring to this [comment](https://github.com/ivadomed/ivadomed/issues/318#issuecomment-650338193) as prepare_dataset_vertebral_labeling was the 'title' 
The 'title' referred to is the header of the section (different options shown [here](https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings)).  The menu create a list with these headers from the .rst file (no header => no link in the navigation bar) 
![image](https://user-images.githubusercontent.com/22171999/87061740-25d57980-c1da-11ea-9519-36cded6849b8.png)



With the title (here H5 title), the documentation will look like this. 
![image](https://user-images.githubusercontent.com/22171999/87060115-20772f80-c1d8-11ea-9ff7-966747cac611.png)

**Comment by jcohenadad** [comment]
ah i see-- i would make the dropdown menu list the exact script name (as they are called in the CLI)

**Comment by lrouhier** [comment]
Right, I guess it's clearer. I' ll change it and open a PR
