### ISSUE TITLE
Documentation about prepackaged model

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#344]
I don't think that we have documentations that points to the pre-trained, pre-packaged multi-center model, which is one of our singularity.

**Comment by charleygros** [comment]
Very good point!
There are already on the ivadomed folder, eg https://github.com/ivadomed/t2star_sc

**Comment by jcohenadad** [comment]
We have now documented the pre-packaged models: https://ivadomed.org/en/latest/pretrained_models.html

Can we close this issue, or did you mean something else @lrouhier ?

**Comment by lrouhier** [comment]
No everything seems perfect !
