### ISSUE TITLE
Create an ivadomed download function

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#346]
instead of having developers and users use curl (e.g. in tutorial, for testing) as we currently advise, we should have an ivadomed downloader. Pros:
- currently, when unpacked, bundled artifacts on github have the name of the release as suffix, which is problematic (we need to manually rename them, creates confusion, etc.)
- having a downloader, we can maintain a database listing the different URLs, mirrors, etc. for each dataset

**Comment by lrouhier** [comment]
Is it a problem to use the [code](https://github.com/neuropoly/spinalcordtoolbox/blob/253936cfc07712c587d9f4cfbbcb760f151172f0/spinalcordtoolbox/download.py#L107) from spinalcordtoolbox for this function ? (not import it to avoid cross dependency but duplicate it)

**Comment by jcohenadad** [comment]
i would be ok with it. @Drulex @kousu ?

**Comment by Drulex** [comment]
I don't see a problem.
