### ISSUE TITLE
Add a .readthedocs.yml to configure build

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#349]
[This doc build fail](https://readthedocs.org/projects/ivado-medical-imaging/builds/11436005/) highlights that many features done by RTD are not necessary (e.g. latex build for epub). Having a config file in our repos might make things easier in the future.

**Comment by dyt811** [comment]
I believe most of these are already implemented by Julien per blame [here](https://github.com/ivadomed/ivadomed/blame/master/.readthedocs.yml) and the [PRs highlighted there](https://github.com/ivadomed/ivadomed/pull/393). Closing.
