### ISSUE TITLE
Save log of terminal printout during training

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#354]
It would be useful to save a log file of the info printed out in the terminal during training. This file could go into the `"log_directory": ` field specified in the config.json file. Intuitively, I would expect to see such log file, given the name of the json field.

**Comment by cakester** [comment]
there is already log.txt that is produced by automated training script, what kind of logs are you looking for?

**Comment by charleygros** [comment]
> 
> 
> on the place where you hope to see more logging, is it only during training or across all existing modules (for Debug/Info etc)?

Training is a good start but would be great to cover all the [possible commands in the main](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/main.py#L283), eg train, test, segment.

> There is currently a log.txt that is produced by automated_training script, is there any additional logs you are looking for?

So yep, when calling `[run_command](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/main.py#L283)` in `main.py`, I think that would be great
