### ISSUE TITLE
log_directory: from config_file to ivadomed flag

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#355]
See idea [here](https://github.com/ivadomed/ivadomed/pull/309#discussion_r453376061)

So the idea would be to run:
```
ivadomed -c <config_file> -o <output_folder>
```

**Comment by lrouhier** [comment]
I Think it was Fixed in #374 (see https://github.com/ivadomed/ivadomed/pull/374#issuecomment-661850799 )

**Comment by charleygros** [comment]
Done in #374
