### ISSUE TITLE
Add test for training_curve script

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#380]
Once testing_data moved to the new repo.

**Comment by lrouhier** [comment]
I tried to implement it (called CLI). The issue is that training curve needs tensorflow, which is not in the requirements... We need to modify that I suppose.

**Comment by jcohenadad** [comment]
> We need to modify that I suppose.

you mean: add the requirement or change something in training_curve to avoid that dependency?

TF is a heavy dependency, buggy, so i'd rather avoid adding it

**Comment by lrouhier** [comment]
I meant that we need to change one or the other. We are looking into a soliution that would not require to use tensorflow as a dependency.
