### ISSUE TITLE
Have ivadomed installed by RTD to avoid having the imports inside conf.py

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#394]
Currently, conf.py includes a lot of ivadomed imports to be able to render the API doc. This is no more necessary with the .readthedocs.yml config file, where ivadomed can be installed with pip there.

**Comment by dyt811** [comment]
This appears to be already implemented many months ago, per [blame record on conf.py here](https://github.com/ivadomed/ivadomed/blame/473c5696ea0fbcd31b1a0e6a6e6b08d672ffa5b2/docs/source/conf.py#L31), which already show very few imports.
