### ISSUE TITLE
Information about used sphinx version

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#428]
We do not provide information about the used sphinx version to built doc locally. The RTD version is fixed to 1.8.5 (for now). The different version can have different behavior so the local doc and the online doc might look different. 
After a discussion with @kousu we have three options:
* Add the information in the wiki
* add right sphinx version to the requirements (note: might conflict with other version and not needed for most users)
* Use setuptools  https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies to create one requirement files that handle two installation (one for doc , one for the rest)
* To create a requirement.txt file under doc to specify which sphinx version we are using. (currently implemented in PR #425) which would work for the online version (but not install it by default)  see https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html. It needs to be used with admin right as specified in the previous link. 

Any preference ?

**Comment by kousu** [comment]
https://docs.readthedocs.io/en/stable/builds.html#understanding-what-s-going-on says 
> Regardless of whether you build your docs with Sphinx or MkDocs, we recommend you pin the version of Sphinx or Mkdocs you want us to use. You can do this the same way [other dependencies are specified](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html). Some examples of pinning versions might be sphinx<2.0 or mkdocs>=1.0.

so they are recommending the fourth option.

You could maybe change .readthedocs.yml to read

```
python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - method: pip
      path: docs/
```

and put this into `docs/requirements.txt`:

```
-r ../requirements.txt
sphinx==1.8.5
```

**Comment by kousu** [comment]
> i would definitely go for "add right sphinx version to the requirements"
> 1: ppl don't read the wiki
> 3: ppl will forget that there is a "special doc install"
> 4: ppl will forget that there is another requirement file

I'm against this option because it means that you'll end overwriting peoples' sphinx versions if they use it, and forcing them to install extra code they don't need if they don't.

It's pretty typical to have multiple sets of dependencies. e.g. https://github.com/scikit-image/scikit-image/tree/536f2c8ba856bf93542e9c64cb943d12d1f90a8d/requirements does it. They use it like this:

https://github.com/scikit-image/scikit-image/blob/536f2c8ba856bf93542e9c64cb943d12d1f90a8d/.github/workflows/build-docs.yml#L22-L26

And for building locally they just document doing `pip install -r requirements/*.txt`:

https://github.com/scikit-image/scikit-image/blob/536f2c8ba856bf93542e9c64cb943d12d1f90a8d/CONTRIBUTING.txt#L198

The people maintaining python's packaging system want us to use option 3: https://github.com/pypa/setuptools/issues/1684#issuecomment-648441338

which would look like adding

```
   extras_require={
    'docs': ["sphinx==1.8.5"],
    },
```

to setup.py, and then triggering it by running `pip install .[docs]`

But I'm unsure if that's compatible with readthedocs. Maybe 

```
python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - method: pip
      path: .[docs]
```

would do it.

((insert perennial complain about python packaging being a mess))

**Comment by kousu** [comment]
You can also sidestep the issue by putting 

```
`--param, -p`
```

instead of what https://github.com/ivadomed/ivadomed/commit/45231e7b55d27e21cadb3991d1f0ef674fcb946e did

```
-\\-param, -p
```

**Comment by jcohenadad** [comment]
> I'm against this option because it means that you'll end overwriting peoples' sphinx versions if they use it, and forcing them to install extra code they don't need if they don't.

isn't that the same argument for all that is listed in the requirements.txt?

**Comment by lrouhier** [comment]
> https://docs.readthedocs.io/en/stable/builds.html#understanding-what-s-going-on says
> 
> > Regardless of whether you build your docs with Sphinx or MkDocs, we recommend you pin the version of Sphinx or Mkdocs you want us to use. You can do this the same way [other dependencies are specified](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html). Some examples of pinning versions might be sphinx<2.0 or mkdocs>=1.0.
> 
> so they are recommending the fourth option.
> 
> You could maybe change .readthedocs.yml to read
> 
> ```
> python:
>   version: 3.6
>   install:
>     - requirements: requirements.txt
>     - method: pip
>       path: docs/
> ```
> 
> and put this into `docs/requirements.txt`:
> 
> ```
> -r ../requirements.txt
> sphinx==1.8.5
> ```

compilation failed see https://readthedocs.org/projects/ivado-medical-imaging/builds/11799110/,  I guess we do need to put in the official requirements ?

**Comment by kousu** [comment]
> > I'm against this option because it means that you'll end overwriting peoples' sphinx versions if they use it, and forcing them to install extra code they don't need if they don't.
> 
> isn't that the same argument for all that is listed in the requirements.txt? (i meant for the 1st argument, not the 2nd one)

Maybe we're talking about different things?

> > https://docs.readthedocs.io/en/stable/builds.html#understanding-what-s-going-on says
> > > Regardless of whether you build your docs with Sphinx or MkDocs, we recommend you pin the version of Sphinx or Mkdocs you want us to use. You can do this the same way [other dependencies are specified](https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html). Some examples of pinning versions might be sphinx<2.0 or mkdocs>=1.0.
> > 
> > 
> > so they are recommending the fourth option.
> > You could maybe change .readthedocs.yml to read
> > ```
> > python:
> >   version: 3.6
> >   install:
> >     - requirements: requirements.txt
> >     - method: pip
> >       path: docs/
> > ```
> > 
> > 
> > and put this into `docs/requirements.txt`:
> > ```
> > -r ../requirements.txt
> > sphinx==1.8.5
> > ```
> 
> compilation failed see https://readthedocs.org/projects/ivado-medical-imaging/builds/11799110/, I guess we do need to put in the official requirements ?

Okay so that was wrong. It's probably supposed to be

```
python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```

I found https://github.com/readthedocs/readthedocs.org/issues/5350 which is helpful; their config [reads](https://github.com/duetosymmetry/qnm/blob/1f5560fe70c6c4afc5ef70ea0c2a3fc57e30a5f3/.readthedocs.yml#L3-L11)

```
python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
```

Curiously, they seem to be using *both* extras (method four) and docs/requirements.txt (method three). However they don't actually define any extras (see [setup.py](https://github.com/duetosymmetry/qnm/blob/4c6c19a84fc91ef24871d034d7ea04a8aea8dca7/setup.py)) so that's just an oversight.

But that is a clue for us!

**Comment by kousu** [comment]
@lrouhier I have a proposed fix in https://github.com/ivadomed/ivadomed/pull/429

**Comment by lrouhier** [comment]
Yeah I get it. I tried the other way around (force the use of sphinx 3.2.1 in the RTD) but the issue I am trying to fix is still not resolved so I am not sure how to check which sphinx version was used for the build...

**Comment by kousu** [comment]
There's another-other fix too:  they have a "feature flag" called [`USE_SPHINX_LATEST`](https://github.com/readthedocs/readthedocs.org/blob/ecac31de54bbb2c100f933e86eb22b0f4389ba84/readthedocs/doc_builder/python_environments.py#L380). I haven't figured out how to turn it on yet, but it's probably settable in .readthedocs.yml.

**Comment by kousu** [comment]
> Yeah I get it. I tried the other way around (force the use of sphinx 3.2.1 in the RTD PR #425 ) but the issue I am trying to fix is still not resolved so I am not sure how to check which sphinx version was used for the build...

as for the problem with the emdashes, what about trying https://github.com/ivadomed/ivadomed/issues/428#issuecomment-686172227 ?

**Comment by lrouhier** [comment]
.



> There's another-other fix too: they have a "feature flag" called [`USE_SPHINX_LATEST`](https://github.com/readthedocs/readthedocs.org/blob/ecac31de54bbb2c100f933e86eb22b0f4389ba84/readthedocs/doc_builder/python_environments.py#L380). I haven't figured out how to turn it on yet, but it's probably settable in .readthedocs.yml.

ok found it it is using the right sphinx version maybe it is a sphinx rtd-theme mismatch ?

**Comment by kousu** [comment]
> There's another-other fix too: they have a "feature flag" called [`USE_SPHINX_LATEST`](https://github.com/readthedocs/readthedocs.org/blob/ecac31de54bbb2c100f933e86eb22b0f4389ba84/readthedocs/doc_builder/python_environments.py#L380). I haven't figured out how to turn it on yet, but it's probably settable in .readthedocs.yml.

Ah nevermind, you have to bug them about it: https://docs.readthedocs.io/en/stable/guides/feature-flags.html

> A separate request can be made by contacting us via email to enable or disable one or more of these featured flags for a particular project.

so that's not a good solution.

**Comment by lrouhier** [comment]
> > Yeah I get it. I tried the other way around (force the use of sphinx 3.2.1 in the RTD PR #425 ) but the issue I am trying to fix is still not resolved so I am not sure how to check which sphinx version was used for the build...
> 
> as for the problem with the emdashes, what about trying [#428 (comment)](https://github.com/ivadomed/ivadomed/issues/428#issuecomment-686172227) ? That should work for all versions.

Yeah But I don't know if that is great visually ( because text is then red and in a separate square)

**Comment by kousu** [comment]
> > > Yeah I get it. I tried the other way around (force the use of sphinx 3.2.1 in the RTD PR #425 ) but the issue I am trying to fix is still not resolved so I am not sure how to check which sphinx version was used for the build...
> > 
> > 
> > as for the problem with the emdashes, what about trying [#428 (comment)](https://github.com/ivadomed/ivadomed/issues/428#issuecomment-686172227) ? That should work for all versions.
> 
> Yeah But I don't know if that is great visually ( because text is then red and in a separate square)

You could write `&hyphen;&hyphen;`?

**Comment by lrouhier** [comment]
I guess Yes somethinhg like this could work (like rst command)

**Comment by lrouhier** [comment]
I have figured out another possible way (but it only deals with the hypen vs endash situation). You can just create a basic command that say that '|--|' represent '--' in html. I did pinned the right shinx version but this is still an issue. I think it comes from the context added to the conf.py file by rtd but I can't seems to test that locally.

**Comment by lrouhier** [comment]
So Basically the version is pinned but then there is some more extension and all that are added so... I am not sure If that is that good. The command is good if we don't have more issue like that. Any thought?

**Comment by lrouhier** [comment]
RTD add some extension andsome command to the conf.py file in the end. The right answer after discussion with Nick seems to use ``--flag``. Eventhough it changes the visual it will allow the user to spot the flag and it won't change between version.

**Comment by kousu** [comment]
> RTD add some extension andsome command to the conf.py file in the end. The right answer after discussion with Nick seems to use `--flag`. Eventhough it changes the visual it will allow the user to spot the flag and it won't change between version.

e.g. in https://readthedocs.org/projects/ivado-medical-imaging/builds/11811212/ the "cat docs/source/conf.py" section shows 

<details>

```
###########################################################################
#          auto-created readthedocs.org specific configuration            #
###########################################################################


#
# The following code was added during an automated build on readthedocs.org
# It is auto created and injected for every build. The result is based on the
# conf.py.tmpl file found in the readthedocs.org codebase:
# https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
#


import importlib
import sys
import os.path
from six import string_types

from sphinx import version_info

# Get suffix for proper linking to GitHub
# This is deprecated in Sphinx 1.3+,
# as each page can have its own suffix
if globals().get('source_suffix', False):
    if isinstance(source_suffix, string_types):
        SUFFIX = source_suffix
    elif isinstance(source_suffix, (list, tuple)):
        # Sphinx >= 1.3 supports list/tuple to define multiple suffixes
        SUFFIX = source_suffix[0]
    elif isinstance(source_suffix, dict):
        # Sphinx >= 1.8 supports a mapping dictionary for multiple suffixes
        SUFFIX = list(source_suffix.keys())[0]  # make a ``list()`` for py2/py3 compatibility
    else:
        # default to .rst
        SUFFIX = '.rst'
else:
    SUFFIX = '.rst'

# Add RTD Static Path. Add to the end because it overwrites previous files.
if not 'html_static_path' in globals():
    html_static_path = []
if os.path.exists('_static'):
    html_static_path.append('_static')

# Add RTD Theme only if they aren't overriding it already
using_rtd_theme = (
    (
        'html_theme' in globals() and
        html_theme in ['default'] and
        # Allow people to bail with a hack of having an html_style
        'html_style' not in globals()
    ) or 'html_theme' not in globals()
)
if using_rtd_theme:
    theme = importlib.import_module('sphinx_rtd_theme')
    html_theme = 'sphinx_rtd_theme'
    html_style = None
    html_theme_options = {}
    if 'html_theme_path' in globals():
        html_theme_path.append(theme.get_html_theme_path())
    else:
        html_theme_path = [theme.get_html_theme_path()]

if globals().get('websupport2_base_url', False):
    websupport2_base_url = 'https://readthedocs.org/websupport'
    websupport2_static_url = 'https://assets.readthedocs.org/static/'


#Add project information to the template context.
context = {
    'using_theme': using_rtd_theme,
    'html_theme': html_theme,
    'current_version': "lr/forgotten_doc",
    'version_slug': "lr-forgotten_doc",
    'MEDIA_URL': "https://media.readthedocs.org/",
    'STATIC_URL': "https://assets.readthedocs.org/static/",
    'PRODUCTION_DOMAIN': "readthedocs.org",
    'versions': [
    ("latest", "/en/latest/"),
    ("stable", "/en/stable/"),
    ("ov-classif_doc", "/en/ov-classif_doc/"),
    ("lr-forgotten_doc", "/en/lr-forgotten_doc/"),
    ("lr-deep_vertebral_labeling", "/en/lr-deep_vertebral_labeling/"),
    ("jca-rtd-config", "/en/jca-rtd-config/"),
    ("cg-tutorial_uncertainty", "/en/cg-tutorial_uncertainty/"),
    ("cg-tutorial_oneclass", "/en/cg-tutorial_oneclass/"),
    ("cg-overview_figure", "/en/cg-overview_figure/"),
    ("al-tutorial_cascaded_architecture", "/en/al-tutorial_cascaded_architecture/"),
    ],
    'downloads': [ 
    ],
    'subprojects': [ 
    ],
    'slug': 'ivado-medical-imaging',
    'name': u'ivadomed',
    'rtd_language': u'en',
    'programming_language': u'words',
    'canonical_url': 'https://ivadomed.org/en/latest/',
    'analytics_code': 'None',
    'single_version': False,
    'conf_py_path': '/docs/source/',
    'api_host': 'https://readthedocs.org',
    'github_user': 'ivadomed',
    'proxied_api_host': '/_',
    'github_repo': 'ivadomed',
    'github_version': 'lr/forgotten_doc',
    'display_github': True,
    'bitbucket_user': 'None',
    'bitbucket_repo': 'None',
    'bitbucket_version': 'lr/forgotten_doc',
    'display_bitbucket': False,
    'gitlab_user': 'None',
    'gitlab_repo': 'None',
    'gitlab_version': 'lr/forgotten_doc',
    'display_gitlab': False,
    'READTHEDOCS': True,
    'using_theme': (html_theme == "default"),
    'new_theme': (html_theme == "sphinx_rtd_theme"),
    'source_suffix': SUFFIX,
    'ad_free': False,
    'docsearch_disabled': False,
    'user_analytics_code': '',
    'global_analytics_code': 'UA-17997319-1',
    'commit': '8c81a77c',
}




if 'html_context' in globals():
    
    html_context.update(context)
    
else:
    html_context = context

# Add custom RTD extension
if 'extensions' in globals():
    # Insert at the beginning because it can interfere
    # with other extensions.
    # See https://github.com/rtfd/readthedocs.org/pull/4054
    extensions.insert(0, "readthedocs_ext.readthedocs")
else:
    extensions = ["readthedocs_ext.readthedocs"]

# Add External version warning banner to the external version documentation
if 'branch' == 'external':
    extensions.insert(1, "readthedocs_ext.external_version_warning")

project_language = 'en'

# User's Sphinx configurations
language_user = globals().get('language', None)
latex_engine_user = globals().get('latex_engine', None)
latex_elements_user = globals().get('latex_elements', None)

# Remove this once xindy gets installed in Docker image and XINDYOPS
# env variable is supported
# https://github.com/rtfd/readthedocs-docker-images/pull/98
latex_use_xindy = False

chinese = any([
    language_user in ('zh_CN', 'zh_TW'),
    project_language in ('zh_CN', 'zh_TW'),
])

japanese = any([
    language_user == 'ja',
    project_language == 'ja',
])

if chinese:
    latex_engine = latex_engine_user or 'xelatex'

    latex_elements_rtd = {
        'preamble': '\\usepackage[UTF8]{ctex}\n',
    }
    latex_elements = latex_elements_user or latex_elements_rtd
elif japanese:
    latex_engine = latex_engine_user or 'platex'

# Make sure our build directory is always excluded
exclude_patterns = globals().get('exclude_patterns', [])
exclude_patterns.extend(['_build'])
```

</details>

that is appended to `docs/source/conf.py`. That page also shows they run sphinx as 

```
python /home/docs/checkouts/readthedocs.org/user_builds/ivado-medical-imaging/envs/lr-forgotten_doc/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

which is similar but potentially subtly different than what `cd docs; make html` does. The biggest difference is that it uses `-b readthedocs` (aka [`readthedocs-sphinx-ext`](https://pypi.org/project/readthedocs-sphinx-ext/)) instead of `-b html`. However there's other subtle changes they make in there, like the part that adds the git commit and the part that adds the table of contents to other branches. After spending a lot of hours digging into it I still don't understand all the ways that do/don't trigger the em-dash processing -- and presumably other things too -- so I think we should give up trying to make the local docs exactly match the readthedocs.org copy.

We *did* pin sphinx in #429 to match what readthedocs is using, so that'll help somewhat, but without also applying their autogenerated config -- a config which they can change at any time without notice -- we'll always be a bit out of sync and I think we just have to accept that and live with it. It's not a huge problem.
