### ISSUE TITLE
Formatting problem for lists

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#438]
commit: a87f8199

Rendering of some lists on RTD is not properly done:
- https://ivadomed.org/en/latest/configuration_file.html#default-model-mandatory
- https://ivadomed.org/en/latest/configuration_file.html#uncertainty

**Comment by lrouhier** [comment]
Started working on it (branch lr/doc_list_format). What do you think about https://ivadomed.org/en/latest/configuration_file.html#scheduler ?
Is this better? 
![image](https://user-images.githubusercontent.com/22171999/93376037-02a4f700-f827-11ea-8fbf-e0eff8d04b52.png)

**Comment by charleygros** [comment]
@lrouhier Yep Züper! Thanks heaps
