### ISSUE TITLE
Questions/comments on tutorials

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#454]
Hi everyone!
I’m beginning to work with ivadomed and I tried the tutorials (with version 2.2.1 in a virtualenv python 3.8). They are great to understand the usage and features of the software. 😊
As a new user, I have a few questions and comments.

[Tutorial 1: One-class segmentation](https://ivadomed.org/en/latest/tutorials/one_class_segmentation_2d_unet.html)
- I trained for only a few epochs on cpu so I can’t compare the results, but otherwise everything works as expected.
- I think it would be worth mentioning the `log_directory` and `num_epochs` parameters of the config file before the training command so the user have an idea beforehand of where the model and metrics will be saved and how long the training will be running.
- In the evaluation part, there is a typo in `log_directory/results/eval/evaluation_3Dmetrics.csv` where `results/eval` should be `results_eval`.
- Also, the section mention twice that test segmentations will be stored in `<log_directory>/pred_masks`.

[Tutorial 2: Cascaded architecture](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html)
- Everything works as expected, except for the display of images in Tensorboard. The “Images” option is “inactive” (drop-down menu) and it says that no image data was found. This is because it works when `debugging` is `true`, but it is set to `false` in the default config file used in the tutorials.
- The field for the parameter `object_detection_params:safety_factor` is not in the default config file and has to be added by the user. I don't know if you would prefer the user to change the value only and not add the entire key+value?

[Tutorial 3: Uncertainty](https://ivadomed.org/en/latest/tutorials/uncertainty.html)

- In the configuration file section, it was not clear to me which config file I should use. I don’t understand the link to “Technical Features” in the first sentence as it is not a link to a config file? I finally used the same default config file as for the first tutorial, changed the appropriate parameters and I have the same output as the one shown in the tutorial.
- In the `log_directory` bullet point, the example is given with `bids_path` key instead of `log_directory` key.

**Comment by andreanne-lemay** [comment]
Thank you so much for your feedback! We will correct the tutorials according to your comments :100:

**Comment by lrouhier** [comment]
Fixed with #461
