### ISSUE TITLE
Correct way to update stored model

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#457]
Some pre-trained models are now stored on a repository (e.g., https://github.com/ivadomed/model_find_disc_t2 ). 
These models are made to be used in spinalcordtoolbox. However, updating the model will increase the size of the repo (it will add the size of the model), which could be a problem. 
Is there a way to update the model's weight without increasing too much the repo size?

**Comment by jcohenadad** [comment]
size of the repos is not a problem because users are downloading release artifacts, not the actual repos-- or am i missing something?

**Comment by lrouhier** [comment]
No you are right. The issue will remain from a developper standpoint. Though it is possible to use git clone --depth 1 to avoid downloading the repo all the time.

**Comment by charleygros** [comment]
After discussing with @lrouhier , it sounds like we can close this issue.
