### ISSUE TITLE
Naming convention for paper related repos

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#469]
Suggestions of naming conventions:
- author1_author2_author3_date
- title_of_the_paper
- free for all

@jcohenadad

**Comment by jcohenadad** [comment]
i've often seen paper repos written with "paper_XX", XX being an obvious identifier for the paper. Eg in your case, something like: `paper_softseg`

**Comment by andreanne-lemay** [comment]
article_softseg looks good to me @charleygros  what do you think?

**Comment by charleygros** [comment]
Oh Yeahh! `paper_softseg` sounds great
