### ISSUE TITLE
Migrate to HDF5 loader

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#474]
ivadomed's adaptive loader currently uses HDF5 to load data and parse metadata. HDF5 allows to load data in RAM or "on the fly". Do we want to migrate ivadomed's loader to HDF5?

**Comment by charleygros** [comment]
After a brief look at `hdf5` documentation and Anthime's code.. I think my preference would be to: (1) generate this pandas dataframe with filenames and images infos by checking data / derivatives availability / suitability (2) split (3) load data as numpy (4) perform preprocessing (5) save preprocessed data etc as HDF5.

**Comment by charleygros** [comment]
A Con of HDF5, I ve just thought about could be the inference on a single image (ie `segment_volume`) --> do we want to systematically move to HDF5 even for this case (ie when used by SCT / ADS) --> it sounds like an "overkill" to me (but maybe it's not?). --> Should we keep the option not to convert data to HDF5 for this case?

**Comment by jcohenadad** [comment]
> After a brief look at hdf5 documentation and Anthime's code.. I think my preference would be to: (1) generate this pandas dataframe with filenames and images infos by checking data / derivatives availability / suitability (2) split (3) load data as numpy (4) perform preprocessing (5) save preprocessed data etc as HDF5.
> A Con of HDF5, I ve just thought about could be the inference on a single image (ie segment_volume) --> do we want to systematically move to HDF5 even for this case (ie when used by SCT / ADS) --> it sounds like an "overkill" to me (but maybe it's not?). --> Should we keep the option not to convert data to HDF5 for this case?

wouldn't it be easy to _not_ have the option to save (ie bypass step 5) and simply use the variables already in RAM to perform prediction?

**Comment by charleygros** [comment]
> wouldn't it be easy to _not_ have the option to save (ie bypass step 5) and simply use the variables already in RAM to perform prediction?

Good idea!!

**Comment by andreanne-lemay** [comment]
After digging into it, I agree with Charley's suggestion.

**Comment by jcohenadad** [comment]
I'm not sure how relevant this is, but I've just came across [this blog against HDF5](https://cyrille.rossant.net/moving-away-hdf5/). Food for thoughts...

**Comment by andreanne-lemay** [comment]
Very interesting post! My thoughts on this:
- "Data corruption": if the software crashes while the hdf5 file is open, the data are corrupted. I personally experienced this issue: if there is an error in the code or if you kill the process, the hdf5 file becomes unreadable. We could simply erase the file with something like a `try ... catch` when it is corrupted or have a closing procedure deleting the file if an error occurred. Since our current solution already loads the data before each process, reloading the data because of a corrupted file is not a real issue here.

- "HDF5 is very complex and low level." I have read that on other blogs as one of the main drawback. For instance:  ["On the con side the CAPI requires detailed understanding of the file format therefore often an easier to use it through python,julia,R, or C++. People with limited training in science/linear algebra are not familiar with HDF5."  ](https://www.quora.com/What-will-be-the-reasons-that-make-you-use-HDF5-instead-of-a-database-What-are-the-pros-and-cons). 

- "Performance issues" and "Poor support on distributed architectures": The current loader doesn't have support for parallel access to data (so not an issue for us). For performance issues, my intuition would be that HDF5 is more efficient than our current loader (since no particular attention was brought to make data access quick and efficient with "smart caching/predictive strategies provided by modern operating systems"), but we would have to validate this. 

- "Opacity": " What is in a file? How many arrays there are? What are their paths, shapes, data types? What is the metadata? Without the HDF5 library, you can't answer any of these questions." Definitely an issue I experienced when working on HeMIS! 

## To balance with cons, here are some pros I found on other blogs:

- On the pro side there is the throughput, low latency, availability for major programming languages and scientific computing platforms, therefore it is ubiquitous in scientific computing and is a better performing alternative to hadoop file system.

(Source: https://www.quora.com/What-will-be-the-reasons-that-make-you-use-HDF5-instead-of-a-database-What-are-the-pros-and-cons)

- HDF5 is very well-known, very well-supported, essentially bug-free, and requires zero support from our team.

- While the format itself is complex, that complexity is irrelevant as long as we define a standard layout and standard metadata.

- C, C++, Fortran, and Python are all natively supported by the HDF5 Group via the HDF5 API

(Source: https://sites.google.com/site/openmodeldata/background-information/existing-solutions/hdf5)

- Another benefit is speed. I haven't ever seen it benchmarked, but HDF is supposed to be faster than SQL databases. I understand that it is very good when used with both large sets of scientific data and time series data - network monitoring, usage tracking, etc.

(Source: https://datascience.stackexchange.com/questions/262/what-are-the-advantages-of-hdf-compared-to-alternative-formats)

**Comment by jcohenadad** [comment]
@kousu @joshuacwnewton @Drulex do you have some insights/experience with dealing with HDF5? Do you have an opinion on this? We are leaning towards adopting it for ivadomed.

**Comment by joshuacwnewton** [comment]
I've used HDF5 a little, but admittedly only for course projects with toy datasets. From what I understand, though, the tradeoffs are very dependent on context, e.g. the dataset (# of images, dimensions of each image, etc.)

[This article](https://realpython.com/storing-images-in-python/) has a very surface-level benchmark, but I have a feeling the data they use to demonstrate (100k small .png images) isn't comparable to what we work with here. (If I understand, our datasets have relatively few subjects, but the images are larger?)

So, the questions I have are mostly to clarify context here:
* What kinds of datasets is IVADOMED intending to support? (e.g. are [OpenNeuro datasets](https://openneuro.org/public/datasets) representative, here?)
* Is there a clear motivation for this change? e.g. Has the current method run into issues with speed, RAM usage, disk usage, etc.? 
* Would we still expecting users to provide a dataset in BIDS format? And then, we'd be using HDF5 as an internal step? (i.e. convert from BIDS -> HDF5, then load from HDF5 internally.) This looks like what `adaptive.py` is doing, but correct me if I'm wrong here.

**Comment by charleygros** [comment]
Thanks for your insights Joshua :-)

>     * What kinds of datasets is IVADOMED intending to support? (e.g. are [OpenNeuro datasets](https://openneuro.org/public/datasets) representative, here?)

Yes this one is quite representative of what we are using at the moment. But we are leaning towards bigger MRI datasets, eg [BraTS](https://www.med.upenn.edu/cbica/brats2019/data.html). And microscopy dataset that are potentially even bigger (@mariehbourget).

>     * Is there a clear motivation for this change? e.g. Has the current method run into issues with speed, RAM usage, disk usage, etc.?

Motivation: We currently have two types of loaders: one on the RAM, one via HDF5 --> we would like to unify them to facilitate the maintenance and the integration of new modalities (for now we dealt with MRI, but we are looking at loading microscopy data that have different data format and RAM needs).
Current issue: we encountered RAM issues in some instances.

>     * Would we still be expecting users to provide a dataset in BIDS format? And then, we'd be using HDF5 as an internal step? (i.e. convert from BIDS -> HDF5, then load from HDF5 internally.) This looks like what `adaptive.py` is doing, but correct me if I'm wrong here.

You are right: we are expecting the user to have a BIDS dataset as input... we refactor it as HDF5 to load it and do our training "on the fly".
At inference time (eg for SCT users), we would not expect a BIDS dataset, but we would still load this single image as a HDF5 .. run the segmentation .. output the nifti

**Comment by joshuacwnewton** [comment]
Thank you for the quick answers! :)

> Current issue: we encountered RAM issues in some instances.

IVADOMED uses PyTorch's `Dataset`/`DataLoader`... hm. I would have assumed that PyTorch would have been smart about this, considering `Dataset`'s `__getitem__` only loads images when needed, and garbage collection should clean up once images are no longer needed. I'm a little surprised there are RAM issues...

Not to go too off-topic here, but... Just out of curiosity, how deeply has this been investigated, e.g. by profiling memory usage? Is there a chance this is due to a memory leak, rather than because of the data loading method? 

> You are right: we are expecting the ivadomed users to have a BIDS dataset as input... we refactor it as HDF5 to load it and do our training "on the fly".

Unless I'm misunderstanding, this results in a full copy of the original dataset. (HDF5 tends to be some multiple larger than the original files, too... There are some [tricky details about compression](https://www.oreilly.com/library/view/python-and-hdf5/9781491944981/ch04.html) here, but admittedly I'm not as well-versed in that.) 

For larger datasets, then, is there a concern here for disk usage? In other words, from a user perspective, would it be surprising for IVADOMED to suddenly be taking up a large amount of space? Or, do we expect our users' environments to be able to handle this?

**Comment by charleygros** [comment]
> Not to go too off-topic here, but... Just out of curiosity, how deeply has this been investigated, e.g. by profiling memory usage? Is there a chance this is due to a [memory leak](https://medium.com/@raghadalghonaim/memory-leakage-with-pytorch-23f15203faa4), rather than because of the data loading method?

I have to admit I did not investigated this thoroughly. Memory leak could definitely be the reason.

> For larger datasets, then, is there a concern here for disk usage? In other words, from a user perspective, would it be surprising for IVADOMED to suddenly be taking up a large amount of space with a copy of the input dataset? Or, do we expect our users' environments to be able to handle this?

I am not too sure about that. I may give the mike to someone else in case they have any ideas.

But overall.. the main motivation for migrating for HDF5 was to have a single loading process, that is compatible with different data format (`.nii.gz` vs. `OME-TIFF`) while allowing to load data either in RAM either "on the fly".

**Comment by mpompolas** [comment]
Hi all.
my understanding after reading the thread is that the transition is needed mostly for maintenance reasons - not really for disk-memory-speed.
As @joshuacwnewton mentioned, you will have to convert the entire dataset to HDF5 before running the model. 
I don't think that this is a big issue for MRI datasets (regarding disk space), although every user case is different.

I designed something similar for Brainstorm when we get datasets from different acquisition systems and need to be spike-sorted (spike-sorters need a specific format as input). The way I approached this:
1. the initial dataset is converted to the spike sorting input and copied to a temp folder
2. perform the spike sorting process, save the information needed.
3. Once everything was done we empty the temp folder in order not to have duplicate datasets

The same idea can be applied here, but substitute spike-sorting with model training.
Depending on how fast the conversion step is, is it justified for your needs to keep the HDF5 file (I would be hesitant to delete the original dataset) after training the model?

> After a brief look at `hdf5` documentation and Anthime's code.. I think my preference would be to: (1) generate this pandas dataframe with filenames and images infos by checking data / derivatives availability / suitability (2) split (3) load data as numpy (4) perform preprocessing (5) save preprocessed data etc as HDF5.

What you described would be step 1.



Regarding the memory issue mentioned above, I'm also a bit surprised. I thought the sole purpose of Pytorch's Dataloader was exactly that, to avoid running out of memory. @joshuacwnewton suggestion for the memory leak might be the case.

Regarding speed, I can't really have an opinion here until we timeit on the MRI datasets. I can tell you from neurophysiology data that there is a big advantage on using HDF5 for loading purposes: I've timed loading a segment from a single channel on 40GB 256 channel recording and the difference between loading the multiplexed binary file and the converted HDF5 was almost 50 times faster.
I have worked with NWB (Neurodata Without Borders file format which is based on HDF5), but only as a user. If we need help with HDF5 I can reach out to the developers.


Personally I am totally in favour of making modular converters to a single file format, and only maintaining that format's input to the model as suggested by @charleygros. This way you can easily expand to more input formats.

**Comment by jcohenadad** [comment]
Based on internal discussions, we decided to close this issue because there is no pressing need for switching to HDF5 for now. This could be reopened in the future if needed.
