### ISSUE TITLE
__ivadomed_dir__ defined twice

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#489]
In PR #484 , `__ivadomed_dir__` is defined in ivadomed/ivadomed/utils.py and ivadomed/ivadomed/config_manager.py. When import this variable from `utils.py` or `__init__.py` circular import issues occur.

**Comment by lrouhier** [comment]
After the refactoring in #497 there will not be any circular dependency (`config_manager` is no longer imported in `utils`). 
I will leave the definition of `__ivadomed_dir__` in `utils.py`

**Comment by charleygros** [comment]
> I will leave the definition of `__ivadomed_dir__` in `utils.py` (see [2550ef3](https://github.com/ivadomed/ivadomed/commit/2550ef3b5dc63652e7fe8d9a02c7ad2c2475c07c))

Sounds good to me!

**Comment by lrouhier** [comment]
Fixed with #497
