### ISSUE TITLE
Set version of dependency

### ISSUE THREAD

**Issue by lrouhier** [ivadomed/ivadomed#501]
It could be in our interest to set the version of the used dependencies in requirements.txt. 
There has already been an issue with h5py (#499) which could happend again with other packages.

**Comment by jcohenadad** [comment]
My suggestion would be to use compatible release "~=" to allow the use of the latest patches in dependent packages, more info in [PEP440](https://www.python.org/dev/peps/pep-0440/#compatible-release)

**Comment by joshuacwnewton** [comment]
FWIW, the approach recommended by PyPA is to keep 2 sets of dependencies: `install_requires` and `requirements.txt`. The former is the minimal requirements needed, while the latter is precise for reproducibility. You can read more about the rationale behind this [here](https://packaging.python.org/discussions/install-requires-vs-requirements/). (As an aside, we kind of use `requirements.txt` for both, but that's beside the point for now...)

The part of the linked page most relevant to us is:

> It is not considered best practice to use `install_requires` to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

So, they seem to suggest that it's worth it to keep dependencies open and flexible, and pin only when things break.

**Comment by joshuacwnewton** [comment]
> My suggestion would be to use compatible release "~=" to allow the use of the latest patches in dependent packages, more info in [PEP440](https://www.python.org/dev/peps/pep-0440/#compatible-release)

Speaking of `~=`, I noticed we didn't use that here: 

https://github.com/ivadomed/ivadomed/blob/82236b96efa126af23362f4b9c8668365d1443f0/requirements.txt#L2

As @jcohenadad mentions, `~=` might be valuable to use here instead of `==`. (I used it over at SCT.)

**Comment by jcohenadad** [comment]
That makes sense @joshuacwnewton, thank you for your insight. Indeed, I was always wondering how we could follow the bleeding edge versions of all dependencies if we specify them (even with the "~=").

**Comment by joshuacwnewton** [comment]
> That makes sense @joshuacwnewton, thank you for your insight. Indeed, I was always wondering how we could follow the bleeding edge versions of all dependencies if we specify them (even with the "~=").

In our case it's tricky, as the material I linked to was written with developers in mind, but our target audience includes both developers and researchers. (Take SCT -- it wants to be both a Python API that developers can build on top of, and also provide CLI scripts that can be used reliably in studies.)  Each audience has different needs, and what works for one might not work for the other. (Flexibility vs. reproducibility.) The challenge is finding a way to balance the two mindsets! :sweat_smile: 

It makes me wonder about having a `pip install` with flexible dependencies for developers, but a release install with fixed dependencies for regular users. Right now our projects are somewhere in the middle, if I understand correctly.

**Comment by jcohenadad** [comment]
> It makes me wonder about having a pip install with flexible dependencies for developers, but a release install with fixed dependencies for regular users.

That would be fantastic. That's what we do for SCT (with a [pip freeze](https://github.com/neuropoly/spinalcordtoolbox/blob/release/requirements-freeze.txt)) and although it takes additional manual steps and diligence for each release, it seems to provide the perfect balance. 

BTW, we could also automatize the pip-freeze step with GH actions...

**Comment by kousu** [comment]
> > It makes me wonder about having a pip install with flexible dependencies for developers, but a release install with fixed dependencies for regular users.
> 
> That would be fantastic. That's what we do for SCT (with a [pip freeze](https://github.com/neuropoly/spinalcordtoolbox/blob/release/requirements-freeze.txt)) and although it takes additional manual steps and diligence for each release, it seems to provide the perfect balance.
> 
> BTW, we could also automatize the pip-freeze step with GH actions...

I know I'm bumping a closed thread here, but: the more you maintain separate "developer" and "user" versions the less reliable either will be. python has a way to handle "developer mode": [`pip install -e`](https://pip.pypa.io/en/stable/cli/pip_install/#editable-installs), and if you want to temporarily pin a version you can change do that in `install_requires` on a branch. If you can use that you get the same versions your users are seeing, but you're able to go in and easily override this or that piece for testing.
