### ISSUE TITLE
Inconsistency between SCT and ivadomed postprocessing names

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#506]
See https://github.com/ivadomed/ivadomed/pull/498#discussion_r517787439

**Comment by dyt811** [comment]
Per @andreanne-lemay's comment [here](https://github.com/ivadomed/ivadomed/pull/498#discussion_r518176145), and the fact that "[keep_largest](https://github.com/ivadomed/ivadomed/search?q=keep_largest)" and "[binarize_prediction](https://github.com/ivadomed/ivadomed/search?q=binarize_prediction)" are now prevalent in the repo, I believe @andreanne-lemay  has already made all the necessary changes by this point. Closing.
