### ISSUE TITLE
Moving documentation images to specific repository

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#511]
As we are building the documentation and adding images, the repository size increases. If we rename/move these images, they still stay in the repository history. Since we want to keep the repos as small as possible, I suggest moving the images to another specific repository: https://github.com/ivadomed/doc-figures

We adopted the [same strategy for SCT](https://github.com/spinalcordtoolbox/doc-figures).

If everyone agrees with this approach, we need to:
- Document this new practice in our internal documentation
- Give credentials to dev team for the new repos (@alexfoias can you please do that)
- Move documentation images to this new repos (@alexfoias)
- For ongoing PR, we need to make this change _before_ the PR and make sure to do a "squash and merge" so the images don't end up in the repos history. Example https://github.com/ivadomed/ivadomed/pull/502/commits/bb0f5477cec0ecd95f904fd06bfaaf14dc3234bd

**Comment by charleygros** [comment]
Thumbs up!

**Comment by alexfoias** [comment]
I granted permissions to team.
I'm working on moving the images, I'll open a PR soon.

**Comment by alexfoias** [comment]
Already done in https://github.com/ivadomed/doc-figures/pull/1 . This issue can be closed.
