### ISSUE TITLE
Make available all stable versions on RTD and display version number below logo

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#515]
On RTD, we should be able to select stable releases:
![image](https://user-images.githubusercontent.com/2482071/98717024-82989a80-235a-11eb-823c-8e96d53aded7.png)

Also, when selecting a stable release, the number should appear (instead of "stable"):
![image](https://user-images.githubusercontent.com/2482071/98717068-93e1a700-235a-11eb-9118-693fcb2e6237.png)

Also see https://github.com/neuropoly/spinalcordtoolbox/issues/3015 for more context and how-to

**Comment by alexfoias** [comment]
I triggered the builds for previous versions.

As for the stable release (the fact that we want the actual number), it's a feature that has been requested but not merged yet. https://github.com/readthedocs/readthedocs.org/issues/4529

For the moment, the default version is set to latest. Not sure if we want to change it to stable.

**Comment by jcohenadad** [comment]
> As for the stable release (the fact that we want the actual number), it's a feature that has been requested but not merged yet. [readthedocs/readthedocs.org#4529](https://github.com/readthedocs/readthedocs.org/issues/4529)

according to @joshuacwnewton it should work, see https://github.com/neuropoly/spinalcordtoolbox/pull/3021/files

**Comment by joshuacwnewton** [comment]
> according to @joshuacwnewton it should work, see https://github.com/neuropoly/spinalcordtoolbox/pull/3021/files

That change just controls whether to show text at all (blank or `stable`/`latest`/etc.)

> Also, when selecting a stable release, the number should appear (instead of "stable"):

Just to clear things up, at SCT, we have this:

![Screenshot from 2020-11-11 09-04-59](https://user-images.githubusercontent.com/16181459/98821167-289ce100-23fd-11eb-8a60-34c14456fb17.png)

* `stable` automatically fetches the latest stable version. It will always display the text `"stable"`.
* `5.0.0` is a tag that was manually activated. It will always display the text `"5.0.0"`.

**Comment by jcohenadad** [comment]
> 5.0.0 is a tag-based build that was manually activated. It will display the text "5.0.0" under the project logo.

this is exactly what we want for ivadomed

**Comment by alexfoias** [comment]
so should we disable latest and stable and just keep the releases ?

**Comment by jcohenadad** [comment]
latest --> master (we need to keep)
stable --> latest release (would be the default, we need to keep)

right @joshuacwnewton ?

**Comment by alexfoias** [comment]
in this case the current setup should work, right ?

**Comment by jcohenadad** [comment]
stable should not show "stable", but the latest version tag. @joshuacwnewton do you know if this is possible? is that what you've implemented in sct?

**Comment by alexfoias** [comment]
I found the info higher 

 As for the stable release (the fact that we want the actual number), it's a feature that has been requested but not merged yet. readthedocs/readthedocs.org#4529

**Comment by jcohenadad** [comment]
> I found the info higher
> 
> `As for the stable release (the fact that we want the actual number), it's a feature that has been requested but not merged yet.`[readthedocs/readthedocs.org#4529](https://github.com/readthedocs/readthedocs.org/issues/4529)

indeed, it was my misunderstanding. I'm OK with the current proposed change.

**Comment by alexfoias** [comment]
We can close this comment.
