### ISSUE TITLE
Generate dataframe for new loader

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#519]
## Context
This issue is part of the loader refactoring project to include microscopy data (#304) and to migrate to HDF5 loader (#474).

Following this [comment](https://github.com/ivadomed/ivadomed/issues/474#issuecomment-708688892), the first step is to generate a dataframe with filenames and images infos by checking data/derivatives availability and associated metadata.

It also aims to remove the dependency to bids_neuropoly.

## Steps to generate dataframe

1. Get a list of all files in BIDS folders starting with `sub*` and ending with specified extensions, including derivatives (ignore json or other files). Questions:
    * Should the extensions be specified as: all extensions compliant with BIDS for supported data_type (anat and microscopy) or extensions specified by user in the config file?
    * Should derivatives include: all files or only files with specified `seg-<label>` (target_suffix) in config file?

2. Parse all entities in filename (`sub`, `ses`, `sample`, `run`, `ce`, `down`, `acq`, `rec`) for supported modalities + `suffix` for modality + `seg-<label>` for derivatives

3. Create a dataframe with 1 line for each file with: `filename`, `all entities’ labels`, `modality`, `data_type`, `filetype`, `seg-<label>`, `absolute_path`, `dataset_root`

4. Read TSV files if present (`participants`, `samples`, `sessions`, `scans`), add columns to dataframe.

5. Read JSON sidecar files, add columns to dataframe.

6. Read appropriate metadata directly from file, depending on the filetype, add columns to dataframe.

## Other considerations

Somewhere, we should check derivatives availability. Currently, the check is done after the split when loading the dataset, both in traditional and adaptative loader. What is best?

We might want to take a look at or use [pybids](https://github.com/bids-standard/pybids) which is a package maintained by BIDS to interact with BIDS datsets.

## Next step

Once the dataframe is done, the next step would be the split which could be done by filtering one or several columns of the dataframe.

**Comment by andreanne-lemay** [comment]
> We might want to take a look at or use [pybids](https://github.com/bids-standard/pybids) which is a package maintained by BIDS to interact with BIDS datsets.

I quickly looked at [ their tutorial ](https://github.com/bids-standard/pybids/blob/master/examples/pybids_tutorial.ipynb) and it seems that pybids does this exact step (query all BIDS params, etc.). I would be in favor of using already existing tools such as pybids. The only thing to consider is that we might have special needs, e.g., in the case microscopy images can't loaded with their tool.

> * Should the extensions be specified as: all extensions compliant with BIDS for supported data_type (anat and microscopy) or extensions specified by user in the config file?
> * Should derivatives include: all files or only files with specified `seg-<label>` (target_suffix) in config file?

From what I understand from `pybids`, if we use their library don't have to make these choices since the parsing is done on their end.

I think it would be wise to invest some time in understanding this tool. It might save us some time in the end.

**Comment by jcohenadad** [comment]
> I would be in favor of using already existing tools such as pybids. 

👍

**Comment by mariehbourget** [comment]
I tested the `pybids` library, and it does cover a lot of operations we want to do to generate the dataframe.

What we can do with it:
-	Create a `BIDSlayout` containing all files present in the BIDS path and including all JSON metadata automatically
-	Create a dataframe with 1 line per path/filename and 1 column per entities and json metadata field
-	Good news, while the microscopy BEP is still in progress and not merged with the BIDS specification, it is possible to use a custom config file to create the layout and parse additional entities for microscopy, as well as skip the BIDS-validator

What it does not do:
-	Derivatives files are indexed but NOT their entities or metadata, the corresponding lines in the dataframe only have the path/filename
-	A `dataset_description.json` file must be present in the `derivatives` or `labels` folder for the indexing to work

Still to be tested:
-	How to read and merge columns from TSV files into the dataframe

Overall, it would be wise to use the pybids library to index the main subjects folders (without derivatives), it will save us a lot of time and will be compliant with other supported modalities (like MEG, EEG) and future modalities.

For the derivatives, I suggest we re-use and adapt the [has_derivatives](https://github.com/neuropoly/bids_neuropoly/blob/2f68174fa85d22aa8927155b5c239b221e96db74/bids_neuropoly/bids.py#L64) and [get_derivatives](https://github.com/neuropoly/bids_neuropoly/blob/2f68174fa85d22aa8927155b5c239b221e96db74/bids_neuropoly/bids.py#L95) functions from bids_neuropoly directly in ivadomed, to pair the image with the groundtruth after the split (same as what is done currently in both the traditional and adaptative loader, example [here](https://github.com/ivadomed/ivadomed/blob/c905522ee6838be4aa40ae1e3d740c8626f6d749/ivadomed/loader/loader.py#L776)).
