### ISSUE TITLE
Add badge pointing to the actual outcome of GitHub actions

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#558]
It would be nice having a badge pointing to the actual outcome of GitHub actions.

**Comment by jcohenadad** [comment]
we should also add other badges (one for each action)

**Comment by lrouhier** [comment]
Are the badges [here](https://github.com/ivadomed/ivadomed/blob/lr/action_badge/README.md) what you expected? 
(Badges Run tests and Publish Package matching the names of our workflows)

**Comment by jcohenadad** [comment]
> Are the badges [here](https://github.com/ivadomed/ivadomed/blob/lr/action_badge/README.md) what you expected?
> (Badges Run tests and Publish Package matching the names of our workflows)

awesome! just the first GH badge should redireect to the actual GH action (currently it points there: https://github.com/ivadomed/ivadomed/workflows/Python%20package/badge.svg)

**Comment by lrouhier** [comment]
Right! except this workflow is an old one (not used for 7 month now) Maybe we can discard it? (the badge was already there before my modification) 
here is the [workflow](https://github.com/ivadomed/ivadomed/actions?query=workflow%3A%22Python+package%22)

**Comment by jcohenadad** [comment]
> Right! except this workflow is an old one (not used for 7 month now) Maybe we can discard it? (the badge was already there before my modification)

ah! yes, let's discard it, it is distracting
