### ISSUE TITLE
Limit file size on commit

### ISSUE THREAD

**Issue by alexfoias** [ivadomed/ivadomed#583]
Problem: we would like to forbid commits that include files bigger than XX MB.
Possible implementations: 

- https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit/39578014#39578014
- https://gist.github.com/kiwidamien/a6a909ee196be8795b30431079074d64

Crossref: https://github.com/neuropoly/spinalcordtoolbox/issues/3100 https://github.com/shimming-toolbox/shimming-toolbox/issues/199 https://github.com/neuropoly/axondeepseg/issues/423

**Comment by kousu** [comment]
https://github.com/neuropoly/spinalcordtoolbox/issues/2705

**Comment by gisellemartel** [comment]
@alexfoias do we have a specific max file size? I am investigating solutions with GitHub actions following the previously linked discussion

**Comment by alexfoias** [comment]
@jcohenadad Could you please let us know what file size limit should we use ?

**Comment by jcohenadad** [comment]
how about 500kB?  Enough for us to catch non-text uploads

**Comment by gisellemartel** [comment]
Closed in #682

**Comment by ssinad** [comment]
I should mention that once a file has been committed, it stays in Git history forever unless the history is rewritten.

**Comment by jcohenadad** [comment]
> I should mention that once a file has been committed, it stays in Git history forever unless the history is rewritten.

indeed, hence this PR

**Comment by ssinad** [comment]
I was thinking of writing an integration test which would fail when the commits contain large files, but it is difficult to track once a commit has been made. Prevention is better than cure, in this case.

**Comment by gisellemartel** [comment]
So the merged changes here will prevent any large files from being committed in the future, but I did not address any large files that may already be in the repository. If the intention was also to remove existing large files I can make another issue for that.
