### ISSUE TITLE
Impossible to modify parameters that are not dict with automate_training

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#587]
When using the CLI `ivadomed_automate_training`, 4 parameters cannot be changed in the hyperparameter file: `gpu`, `command`, `log_directory`, `model_name`, and `debugging`. The script assumes that the parameters changed will be dictionaries due to [this line](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/automate_training.py#L186), and the parameters mentioned above are not dictionaries.

This issue should be fixed. All parameters should have the option to be modified with `ivadomed_automate_training`.

see [comment](https://github.com/ivadomed/ivadomed/pull/586#pullrequestreview-554209935)

**Comment by ahill187** [comment]
Right, I actually noticed that issue when I was trying to write tests for `automate_training.py`. I can take a look after I've finished?

**Comment by andreanne-lemay** [comment]
Yes, absolutely! Thank you @ahill187

**Comment by ahill187** [comment]
Just taking a look at the `automate_training.py`, from my preliminary understanding, it creates combinations of the different hyperparameters, and then runs training on all the different options? Since the code uses the `gpu_ids` list to do parallel processing, I'm not sure it makes sense for that one to be a hyperparameter?

**Comment by andreanne-lemay** [comment]
Yep, absolutely! But maybe, we would want to have different `model name`s or maybe specific gpus according to other hyperparameters. This is not a pressing issue since the 4 parameters that can't be changed with automate_training are not crucial (or typically used for hyperparametrisation). It would be cleaner to not have this restriction and let it in the hands of the user to choose what parameters should be changed in the config file.

**Comment by ahill187** [comment]
Ah okay. I also have a question about the intended function of `multi_params`. So suppose the `initial_config` is this:

```
      {
          "training_parameters": {
              "batch_size": 18,
              "loss": {"name": "DiceLoss"}
          },
          "default_model":     {
              "name": "Unet",
              "depth": 3
          }
      }
```

And our hyperparameters file is this:
```
      {
        "training_parameters": {
          "batch_size": [2, 64],
          "loss": [
            {"name": "DiceLoss"},
            {"name": "FocalLoss"}
          ],
        },
        "default_model": {"depth": [2, 3]}
      }
```

If we selected `multi_params`, does that apply to all the categories, or just within a category, i.e., should it be:

```
    batch_size = 2, loss = DiceLoss, depth = 2
    batch_size = 64, loss = FocalLoss, depth = 2
    batch_size = 2, loss = DiceLoss, depth = 3
    batch_size = 64, loss = FocalLoss, depth = 3
```

or 

```
    batch_size = 2, loss = DiceLoss, depth = 2
    batch_size = 64, loss = FocalLoss, depth = 3
```
?

**Comment by andreanne-lemay** [comment]
Yes, good question. It would be the second option: a list of two items, will generate 2 configuration files. Let me know if there would be a way to make this clearer. I agree the description is not super intuitive.

**Comment by ahill187** [comment]
Okay perfect thank you! Just wanted to make sure I had the intended functionality correct before refactoring :) I'm going to add more of an explanation to the docstrings, and also some tests to test the different options. Thanks for your help!!
