### ISSUE TITLE
Clarify multi-GPU usage in documentation

### ISSUE THREAD

**Issue by leandervaneekelen** [ivadomed/ivadomed#589]
Currently, training a model with the standard `ivadomed --config config.json` syntax doesn't support multi-GPU usage; this is only meant for `ivadomed_automate_training`. 

I found [this page](https://github.com/ivadomed/ivadomed/wiki/pipeline-training-and-model-comparison)  on the dev wiki explaining the usage of the `ivadomed_automate_training` and the syntax for multi-GPU usage; perhaps we can use this and link it in the [RTD page](https://ivadomed.org/en/latest/configuration_file.html#gpu) that covers the configuration file?

**Comment by ahill187** [comment]
I'm wondering if maybe we should refactor the `gpu` argument to always be a list?
So, for `automate_training`, it might be:
```[1,2,3,4]```
and for the other files it would be:
```[1]```
