### ISSUE TITLE
Add a wiki page for naming conventions of variables

### ISSUE THREAD

**Issue by ahill187** [ivadomed/ivadomed#593]
## Description

The `Spinal Cord Toolbox` has a wiki page for naming conventions of our variables in the code; we would like to add a similar page to `ivadomed`:

https://github.com/neuropoly/spinalcordtoolbox/wiki/Programming%3A-Variables#variables

**Comment by gisellemartel** [comment]
@ahill187 would you happen to know if code naming conventions intended to be uniform across both the `Spinal Cord Toolbox` and `Ivadomed` projects?

**Comment by jcohenadad** [comment]
> @ahill187 would you happen to know if code naming conventions intended to be uniform across both the Spinal Cord Toolbox and Ivadomed projects?

Yes, we are trying (hard) to harmonize conventions across projects. Tagging @joshuacwnewton as he is overseeing these aspects

**Comment by joshuacwnewton** [comment]
> Yes, we are trying (hard) to harmonize conventions across projects.

Within reason, of course! And only if the effort is worth the benefit... :sweat_smile: 

> Tagging @joshuacwnewton as he is overseeing these aspects

For something as relatively minor as variable names, I don't think too much discussion is needed. As long as folks are making Wiki pages at all (and referring to them consistently within a project), then that's the key. It's okay to whip something up then revise later. :slightly_smiling_face: 

e.g. For something as small as this, it's safe for someone to just go ahead and draft a page in 5m, then discuss that draft informally on Slack after the fact. Heck, you could even start by straight up copying SCT's page! No need to ping me before getting started. :sweat_smile: 

I refer to this a lot, but a quote from [this blog post](https://www.danclarke.com/internal-developer-documentation) really captures my feelings here:

> I'm talking about internal technical developer documentation in which devs can be free to add to and update existing documentation. **It should be easy and effortless to do so, without friction that would come from updating publicly released product documentation.**

**Comment by jcohenadad** [comment]
Thank you for your insights @joshuacwnewton. Maybe I should add that another strong benefit of harmonizing practices across projects is that students/developers sometimes end up working on multiple projects, so it makes code reading much easier at the end.

**Comment by gisellemartel** [comment]
Thanks for the feedback @jcohenadad @joshuacwnewton. I've begun an initial draft for this in the wiki similar to what is in the SCT wiki. This ticket only refers to Variables, but I believe also including conventions related to coding style, commenting, etc. would be a good idea too, perhaps I can tackle that at the same time?

**Comment by jcohenadad** [comment]
> I've begun an initial draft for this in the wiki similar to what is in the SCT wiki.

could you please open a PR and cross-ref it here? many thanks!

**Comment by gisellemartel** [comment]
@jcohenadad I tried to do this but I believe PRs are not possible for the wiki, since the wiki docs technically reside outside the ivadomed git repo

**Comment by joshuacwnewton** [comment]
> @jcohenadad I tried to do this but I believe PRs are not possible for the wiki, since the wiki docs technically reside outside the ivadomed git repo, unless we have some sort of automated build process set-up, which I do not believe is the case? See here for example: https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

+1 to this. Similar conclusion reached here: https://github.com/neuropoly/spinalcordtoolbox/issues/2880

**Comment by gisellemartel** [comment]
Will close this issue now that we have a first draft for wiki concerning variables (and other code conventions), and since we also appear to have #629 that also covers the scope of this ticket.
