### ISSUE TITLE
What is "painted" data in the evaluation module?

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#611]
Here:
https://github.com/ivadomed/ivadomed/blob/fbfbfcc4d91f91d0d6e974001a0c87a48f33f059/ivadomed/evaluation.py#L72

It is unclear what "painted" data means. Comment before the code should probably be extended.

Related to that, when doing the [evaluation in this tutorial](https://ivadomed.org/en/latest/tutorials/one_class_segmentation_2d_unet.html#evaluate-model), under "pred_masks", I see the same pairs of segmentations, e.g.: 
~~~
sub-strasbourg04_T2w_pred.nii.gz --> 64bit int
sub-strasbourg04_T2w_pred_painted.nii.gz  -> 64bit float
~~~
What is the motivation behind outputting the two segmentations? Maybe that could be documented in the tutorial (users going through the tutorial will wonder why 2 files?). 

Also (maybe could be addressed in another issue): the quantization differs between the two (64bit int/float). Don't we want UINT8 for binary segmentations?

**Comment by ahill187** [comment]
I'm still very new to these files, but I followed the tutorial and used the software [MRIcron](https://www.nitrc.org/projects/mricron) to open the files, and only the `_painted` files worked?

**Comment by jcohenadad** [comment]
Duplicate of https://github.com/ivadomed/ivadomed/issues/1229
