### ISSUE TITLE
ivadomed CLI: Unclear what -g expects

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#613]
To give an example of what I went through when trying to use the -g flag for the ivadomed CLI:
~~~
(venv) p101317@rosenberg:~/ivadomed_training$ ivadomed -c config_bn0.1.json -g
ivadomed: error: argument -g/--gif: expected one argument
(venv) p101317@rosenberg:~/ivadomed_training$ ivadomed -c config_bn0.1.json -g training.gif
usage: ivadomed -c CONFIG [-g GIF] [-t THR_INCREMENT] [--resume-training] [-h]
ivadomed: error: argument -g/--gif: invalid int value: 'training.gif'
(venv) p101317@rosenberg:~/ivadomed_training$ ivadomed -c config_bn0.1.json -g 1
~~~

Usage should be clarified. Also, i'm not a big fan of using "0/1" for -g. Why not use "store_true" argparse option?

**Comment by charleygros** [comment]
@jcohenadad `-g` receives a int --> `-g 10` leads to 10 GIFs, ie 10 slices randomly taken in the training set, cf:
```
  -g GIF, --gif GIF     Generates a GIF of during training, one frame per
                        epoch for a given slice. The parameter indicates the
                        number of 2D slices used to generate GIFs, one GIF per
                        slice. A GIF shows predictions of a given slice from
                        the validation sub-dataset. They are saved within the
                        log directory.
```

How would you suggest to improve this documentation?

**Comment by charleygros** [comment]
> Also, i'm not a big fan of using "0/1" for -g. Why not use "store_true" argparse option?

As `-g` can accept int > 1, should I use `store_const` instead of `store_true`?

**Comment by jcohenadad** [comment]
ah! i completely misunderstood the usage-- my fault by reading it too fast 😬  -- but it suggests that others might also read too fast and misunderstand as well, so we could possibly change the wording to avoid confusion.

I think i got confused by seeing: 
~~~
-g GIF, --gif GIF     Generates a GIF of during training, blablabla
~~~
and my brain automatically translated "if i use '-g' I get gif 🥳", without reading the blablabla (again: my fault, i apologize).

To mitigate this possible confusion, I would suggest to directly address the role of the parameter, e.g.:
~~~
Number of GIF files to output. Each GIF file corresponds to a 2D slice showing the prediction over epochs (one frame per epoch). The prediction is run on the validation dataset. GIF files are saved in the log directory. 
~~~

**Comment by jcohenadad** [comment]
A further usage help is proposed in https://github.com/ivadomed/ivadomed/issues/627 (separate issue)
