### ISSUE TITLE
Center cells in purpose

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#617]
Here: https://ivadomed.org/en/latest/purpose.html#comparison-with-other-projects

It would be nice to have text in the cells centred (like the green checks / red cross).

**Comment by gisellemartel** [comment]
@jcohenadad latest commit seems to have resolved the issue! Just make sure to empty the browser cache before reloading https://ivado-medical-imaging--619.org.readthedocs.build/en/619/purpose.html

**Comment by gisellemartel** [comment]
Resolved in #619
