### ISSUE TITLE
Duplicate images in sct_testing/large

### ISSUE THREAD

**Issue by olix86** [ivadomed/ivadomed#65]
While investigating why we had identical metrics on different datasets in #63, I stumbled on the fact that images from different patients seem to be duplicated in sct_testing/large

Steps to reproduce :
`cd /duke/sct_testing/large`

Then the following computes hashes and groups duplicates them together
`find -not -empty -type f -printf "%s\n" | sort -rn | uniq -d | xargs -I{} -n1 find -type f -size {}c -print0 | xargs -0 md5sum | sort | uniq -w32 --all-repeated=separate`

[Source](https://www.maketecheasier.com/remove-duplicate-files-linux/)

Example output : 

>
```
f0677d577875bfba06b695ec011ed1d8  ./sub-grenobleOfsep007/anat/sub-grenobleOfsep007_acq-sag_T2w.nii.gz
f0677d577875bfba06b695ec011ed1d8  ./sub-grenobleOfsep068/anat/sub-grenobleOfsep068_acq-sag_T2w.nii.gz

f10aa736034209eee5faca578ad769bd  ./sub-grenobleOfsep004/anat/sub-grenobleOfsep004_acq-sag_T2w.nii.gz
f10aa736034209eee5faca578ad769bd  ./sub-grenobleOfsep071/anat/sub-grenobleOfsep071_acq-sag_T2w.nii.gz

62f71ef2e6230f25c88fa3c55b9451b4  ./sub-montpellierLesion011/anat/sub-montpellierLesion011_acq-sagcerv_T2w.nii.gz
62f71ef2e6230f25c88fa3c55b9451b4  ./sub-rennesMS042/anat/sub-rennesMS042_acq-sagcerv_T2w.nii.gz

```

**Comment by alexfoias** [comment]
@jcohenadad Do we still have to address this issue ? Maybe @mpompolas or @kousu can give us some feedbakcin case we have duplicates ? Otherwise I can check it with `fdupes`

**Comment by jcohenadad** [comment]
Can you check please? thank you

**Comment by alexfoias** [comment]
I checked, there are no duplicates in sct-testing-large repo.

Proof here: http://showterm.io/13f1eb7c081908215338c

We can close the issue.
