### ISSUE TITLE
Include ivadomed version in JSON config file and check for compatibility

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#654]
As ivadomed is being continuously improved, we are sometimes changing fields in the [config file](https://ivadomed.org/en/latest/configuration_file.html). These changes can break retro-compatibility.

It would be great to find a mechanism to inform the user if the config file they are using (which could be based on an 6-month old ivadomed version) is still compatible with the most recent ivadomed release.

A suggestion, would be to add a field in the config file (another one 😅 ), which states the version of ivadomed the config file was based on, e.g.:
~~~
{
    "ivadomed_version": "v2.6.0"
} 
~~~

And in ivadomed, when loading the config file, we could create an API that would parse this version and verify if it is compatible with the current ivadomed version. The way we could do it, is, if at some point in history some fields in the config file are changed, then we would update this API to add the release as a "retro-compatibility breaking point". 

So with this strategy, we need to make sure that every time the config file is changed, the API is updated.

Suggestions welcome!

**Comment by andreanne-lemay** [comment]
Currently, we have a [configuration file manager](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/config_manager.py) that helps with retrocompatibility. If new parameter is required or if a key is changed, this class deals with "old" config files to avoid retrocompatibility breakage. I think this class covers the purpose you're describing, but if not we can always add options to the ConfigurationManager.

**Comment by jcohenadad** [comment]
Fantastic! i was not aware of this config file manager. I suppose it does serve the exact purpose of my issue then 😊

**Comment by ssinad** [comment]
> As ivadomed is being continuously improved, we are sometimes changing fields in the [config file](https://ivadomed.org/en/latest/configuration_file.html). These changes can break retro-compatibility.
> 
> It would be great to find a mechanism to inform the user if the config file they are using (which could be based on an 6-month old ivadomed version) is still compatible with the most recent ivadomed release.
> 
> A suggestion, would be to add a field in the config file (another one 😅 ), which states the version of ivadomed the config file was based on, e.g.:
> 
> ```
> {
>     "ivadomed_version": "v2.6.0"
> } 
> ```
> 
> And in ivadomed, when loading the config file, we could create an API that would parse this version and verify if it is compatible with the current ivadomed version. The way we could do it, is, if at some point in history some fields in the config file are changed, then we would update this API to add the release as a "retro-compatibility breaking point".
> 
> So with this strategy, we need to make sure that every time the config file is changed, the API is updated.
> 
> Suggestions welcome!

On a somewhat related note, backward compatibility breaking point is when the major version number must be incremented, according to the [semantic versioning specification](https://semver.org/), e.g. v2.6.0 becomes v3.

**Comment by ssinad** [comment]
I would also suggest keeping a [changelog](https://en.wikipedia.org/wiki/Changelog).

**Comment by jcohenadad** [comment]
> I would also suggest keeping a [changelog](https://en.wikipedia.org/wiki/Changelog).

👉  https://github.com/ivadomed/ivadomed/blob/master/CHANGES.md
