### ISSUE TITLE
Pybids warning for derivatives in new loader

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#660]
Following this [comment](https://github.com/ivadomed/ivadomed/pull/648#issuecomment-769325836).

[Here](https://github.com/ivadomed/ivadomed/blob/cd37576ec23a1a540b4ce516e244f71ea76690bf/ivadomed/loader/utils.py#L797), when derivatives is True, the `pybids` dependency returns a UserWarning if a “dataset_description.json” file is not present in the `bids_path/derivatives` or the `bids_path/derivatives/labels` folder.
As a result, the derivatives are not indexed in the dataframe.

<details>
  <summary>Warning from pybids</summary>
 
``` 
/venv-ivadomed-38c/lib/python3.8/site-packages/bids/layout/validation.py:119: UserWarning: Derivative indexing was requested, but no valid datasets were found in the specified locations (['ivadomed/data_example_spinegeneric/derivatives']).
Note that all BIDS-Derivatives datasets must meet all the requirements for BIDS-Raw datasets (a common problem is to fail to include a 'dataset_description.json' file in derivatives datasets). 
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2", "PipelineDescription": {"Name": "Example pipeline"}}
```
</details>

If the file is missing, we would like to write it in the `bids_path/derivatives` folder.
As a reference, the minimal content of the file must be:
`{"Name": "Example dataset", "BIDSVersion": "1.0.2", "PipelineDescription": {"Name": "Example pipeline"}}`

**Comment by gisellemartel** [comment]
@mariehbourget I am trying to reproduce the warning but am unable to. Would you be able to provide repro steps such as config file that was used and if one of the scripts was used?

**Comment by mariehbourget** [comment]
The new loader is not working yet on master branch because of the recently merged PR for multiple folders, you'll have to checkout my new branch first.

Steps to reproduce:
1. `cd ivadomed`
2. `git checkout mhb/new-loader-multiple-folders`
3. Download data_example_spinegeneric `ivadomed_download_data -d data_example_spinegeneric`
4. Run `python df_new_loader.py` script (it uses the `ivadomed/config/config_new_loader.json` config file)
