### ISSUE TITLE
change_keys method in ConfigurationManager not working for python 3.8 and over

### ISSUE THREAD

**Issue by andreanne-lemay** [ivadomed/ivadomed#673]
This method works well for python 3.7 and under, but this error occurs when using python3.8:
```
RuntimeError: dictionary keys changed during iteration
```
This could be fixed by passing the keys (copy) and the context (reference), instead of getting the keys from the context.

**Comment by ssinad** [comment]
This error usually occurs when you add to or remove elements from an iterable while looping over it. It is a better practice to make a copy of the original container and modify that one. Can you include where this is happening in code?

**Comment by andreanne-lemay** [comment]
The error occurs here: https://github.com/ivadomed/ivadomed/blob/master/ivadomed/config_manager.py#L110. 
I know / understand why there is an error. It currently works so I simply opened an issue (it's on my todo list). Passing a copy defies the purpose of the method which is to modify the dictionary (if I pass a copy the object won't be modified). Passing a copy of the keys should solve the problem.
