### ISSUE TITLE
Auto download pytest testing data files if missing to facilitate fully automated testing anywhere

### ISSUE THREAD

**Issue by dyt811** [ivadomed/ivadomed#704]
### Motivation for the feature

- Currently, testing with pytest require manually downloading the test data via console commands (at least according to the [readme.md in the /testing directory](https://github.com/ivadomed/ivadomed/blob/master/testing/README.md)), [even though automated via YAML on GithHub/TravisCI](https://github.com/ivadomed/ivadomed/blob/master/.github/workflows/run_tests.yml#L47). Earlier issue recommends an automated approach. See #337 

### Description of the feature

0. Build the following as pytest session level fixture required for most existing pytests (**every single test_*.py related to test files needs to add the new fixture as an argument;** ```@pytest.fixture(scope='session')``` decorator needed for the fixture function)
1. Call the existing t_utils.py [download_dataset function](download_dataset): it has builtin check for some of the existing pytest data folders (/data_testing, not sure about /data_functional_testing? Will have to experiment a bit more)
3. Do another sanity check to ensure download success (in case no internet/service outage, etc) to prevent crashing subsequent pytests. 
4. Continue pytest as usual 
5. (Optional) Delete/clean up the test data file (/tmp file already cleaned up by test)? Not sure if this is required as 1) only devs run pytests usually. 2) no need to do this on TravisCI etc. Not sure how likely user will run pytest on repo. 

### Alternatives

- One possible alternative solution (i.e. less decorator/argument clutter) could be using [pytest_session_start ](https://docs.pytest.org/en/stable/reference.html#pytest.hookspec.pytest_sessionstart) and [pytest_sessionfinish](https://docs.pytest.org/en/stable/reference.html#pytest.hookspec.pytest_sessionfinish), as examples shown [here](https://stackoverflow.com/a/66283728). 
   - **Pro**: 
      - overall, cleaner syntax, no need to change any existing @pytest calls/signatures or add any fixtures. 
   - **Con**: 
      -  this implementation and similar to existing implementation, are not making the requirement/assumption explicit for the unit tests 
      - **Having an actual reference (in signature/decorator) to the required fixture will force whoever come across to realize 1) this unit test has dependencies requirement for it to succeed, 2) it cannot exist as a stand alone tests.** This can then be evaluated simply by looking at unit test decorators, where as currently, no way to distinguish stand alone unit tests versus those that have file requirement without digging into the code. 
      - "Explicit is better than implicit" per PEP20. 
- I am flexible on the final implementation choice as long as the standard/same guideline is carried on going forward.    

### Additional context

- It will **make dockerized pytest very easy**, in essence unify how pytest for the repos are done anywhere (assuming dependencies are already met)
- Being a bit OCD/detail focused here on seeming minor issue because 1) **it will impact all branches/PR/CI, future new tests,** etc. Very important to get **consensus** on this issue before plowing ahead  to code up the relatively straight forward solution
- It will be **compatible with all existing TravisCI integratio**n as already have test data file there will simply skip downloading and result in no tangible CI differences but help with local pytest, especially new developers/students/users who run pytest(!?). 
- If settled, this should go into **coding standard guideline** on all additional unit tests require data (new models, data loaders etc)
- Probably gonna be the first PR from a series of CI/test related changes from me so better safe than sorry 😆

**Comment by jcohenadad** [comment]
Relevant discussion: https://github.com/neuropoly/spinalcordtoolbox/pull/3152#discussion_r554063565
