### ISSUE TITLE
Refactoring: reduce complexity of BidsDataset __init__ for loop

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#719]
As commented [here](https://github.com/ivadomed/ivadomed/pull/699#discussion_r590564613), there is a lot of code nested within the for loop in BidsDataset [here](https://github.com/ivadomed/ivadomed/blob/0a4b7bb3fad8092b31b347332b16f5308be09a54/ivadomed/loader/loader.py#L837).
We should check if there is a way to extract some of the logic into other functions for better readability.

**Comment by gisellemartel** [comment]
Linking also this issue since it is closely relate: #694
