### ISSUE TITLE
Un-silence a unit test: test_rgb.py

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#720]
### Context

While working on https://github.com/ivadomed/ivadomed/pull/714, I had to silence the function `save_color_labels` because the way it was implemented produced an error when the header of the reference image was copied to the output prediction. Namely, the field "dtype" was not compatible, yielding the following error when saving the  NIFTI file:
~~~
>           raise WriterError('Cannot cast to or from non-numeric types')
E           nibabel.arraywriters.WriterError: Cannot cast to or from non-numeric types
~~~

### TODO

- Fix the implementation of `save_color_labels`
- Reestablish the calls to this function, which were removed in https://github.com/ivadomed/ivadomed/pull/714/commits/52079bd339b6e0cdffa61b778da2bae9a3560e55
- I had to silence a test (see this commit https://github.com/ivadomed/ivadomed/pull/714/commits/0f946fc3fe4b083d33783fe96a4be5e9ed207558), which was lower priority compared to the PR. This silenced test should be revisited.

**Comment by cakester** [comment]
how do I properly fix ```save_color_labels```?

**Comment by cakester** [comment]
the problem right now is that  input array dtype is [('R', 'u1'), ('G', 'u1'), ('B', 'u1')], but the gt_file dtype is float32, when the file header is copied to nib object it doesn't match the data dtype, before the header is not copied so it uses the input array dtype instead. Now the first thing to do is to find a nii.gz file with the right dtype

**Comment by cakester** [comment]
changed a gt_file with the right dtype in header, it worked
