### ISSUE TITLE
Remove merge_bids_dataset from loader/utils.py

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#726]
With the integration of the new loader (#699), the function [merge_bids_dataset](https://github.com/ivadomed/ivadomed/blob/0a4b7bb3fad8092b31b347332b16f5308be09a54/ivadomed/loader/utils.py#L575) from `loader/utils.py` is not used anymore.

The `participants.tsv` file created by the function was used by `scripts/visualize_and_compare_testing_models.py` in opened PR #572, and could be replaced by the `bids_dataframe.csv` file saved in the output directory with the new loader (tagging @mpompolas).

The `merge_bids_dataset` function is the last function dependent on `bids_neuropoly` in the codebase. If we remove it, we should also remove `bids_neuropoly` from `requirements`.

**Comment by mpompolas** [comment]
Hi @mariehbourget, you can remove this function. I will change https://github.com/ivadomed/ivadomed/pull/572 to accommodate your changes
