### ISSUE TITLE
python3.9 incompatibility due to onnxruntime

### ISSUE THREAD

**Issue by kousu** [ivadomed/ivadomed#740]
ivadomed doesn't install on python3.9 because onnxruntime is pinned to an old version that 

a. doesn't provide packages for 3.9: https://pypi.org/project/onnxruntime/1.4.0/#files
b. doesn't even provide an `sdist` for anything

```
(venv) [kousu@requiem ivadomed]$ pip install -e .
Obtaining file:///home/kousu/src/neuropoly/ivadomed
Collecting bids-neuropoly>=0.2
  Using cached bids_neuropoly-0.2-py3-none-any.whl (3.1 kB)
Collecting csv-diff>=1.0
  Using cached csv_diff-1.1-py3-none-any.whl (12 kB)
Collecting h5py==2.10.0
  Using cached h5py-2.10.0.tar.gz (301 kB)
Collecting joblib
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting matplotlib>=3.3.0
  Using cached matplotlib-3.4.0-cp39-cp39-manylinux1_x86_64.whl (10.3 MB)
Collecting nibabel
  Using cached nibabel-3.2.1-py3-none-any.whl (3.3 MB)
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.4.0 (from ivadomed)
ERROR: No matching distribution found for onnxruntime==1.4.0
```

Their latest version https://pypi.org/project/onnxruntime/1.7.0/#files does provide 3.9 packages.

**Comment by kousu** [comment]
(I realize python3.9 support isn't on the roadmap yet but some of us are out here already and it's good to see what's coming ahead)

**Comment by dyt811** [comment]
Good point. I am going to get someone to start thinking about how to update the GitHub Actions in anticipation of bigger matrix testing.

**Comment by dyt811** [comment]
Going to start investigate this along with the Windows GitHub Action integration testing for IvadoMed as part of a PR for CI improvement.

**Comment by joshuacwnewton** [comment]
Repeating what I said in https://github.com/ivadomed/ivadomed/issues/770#issuecomment-830979421 here:

> We pin `onnxruntime==1.4.0` because newer versions depend on `libomp`, and we didn't want to have to ask users to `brew install libomp`. See: https://github.com/neuropoly/spinalcordtoolbox/issues/3033, https://github.com/microsoft/onnxruntime/issues/5344.
>
> We could unpin this, but we would need a plan for communicating the `libomp` dependency to users.
