### ISSUE TITLE
Drop bids_neuropoly

### ISSUE THREAD

**Issue by kousu** [ivadomed/ivadomed#742]
`bids_neuropoly` has been superseded by pybids, but it is still used in this one tiny spot:

https://github.com/ivadomed/ivadomed/blob/d9a5bdb652dd79e588dcf7988b7fae8e6ecf8be8/requirements.txt#L1

https://github.com/ivadomed/ivadomed/blob/d9a5bdb652dd79e588dcf7988b7fae8e6ecf8be8/ivadomed/loader/utils.py#L9

https://github.com/ivadomed/ivadomed/blob/d9a5bdb652dd79e588dcf7988b7fae8e6ecf8be8/ivadomed/loader/utils.py#L587

Can that be replaced by pybids? It would simplify deployments.

**Comment by jcohenadad** [comment]
Possibly related to #726

**Comment by charleygros** [comment]
> Can that be replaced by pybids? It would simplify deployments.

Just tagging @mpompolas (:

**Comment by mpompolas** [comment]
as @jcohenadad mentioned, it is related to #726.

This function was introduced for https://github.com/ivadomed/ivadomed/pull/572.
Wait for @mariehbourget to remove it as long as she does not need it with the new loader and I will accommodate the changes on #572

**Comment by kousu** [comment]
Nice. So this is essentially a duplicate of #726 then!
