### ISSUE TITLE
Data-loader error for intervertebral disc labeling 

### ISSUE THREAD

**Issue by rezazad68** [ivadomed/ivadomed#772]
I am facing with loading error for intervertebral disc labeling using `ivadomed`. I am using the latest version (`2.7.4`) of `ivadomed` and already tried the sample 2D segmentation example (`ivadomed -c config.json`) and it works fine. However, intervertebral disc labeling generates a loader error. I have double-checked the address but still doesn't work.  the screenshot is attached. 

![vertebral loading error](https://user-images.githubusercontent.com/20574689/116520838-894ca700-a8d3-11eb-82f3-550af5222dfa.png)

**Comment by mariehbourget** [comment]
Hi @rezazad68!
I can help you with that, it is most likely a BIDS compliance issue with the dataset.
Can you send me your config file? I would also need to check the filenaming in the dataset, is it available somewhere on duke?

**Comment by rezazad68** [comment]
Thanks for the response.
I uploaded [here](https://github.com/rezazad68/DeepSpine/blob/main/images/config_vertebral_labeling.json)
I am using the Spine Generic Dataset. 
https://github.com/spine-generic/data-multi-subject

**Comment by jcohenadad** [comment]
@rezazad68 it would be great if you could use both the spine generic dataset and our internal sct-testing-large data. The way to do this properly would be to:
- have your processing script run on spine-generic and generate the "new" BIDS dataset and package it with git-annex-- @kousu will help
- have your processing script run on sct-testing-large and generate the "new" BIDS dataset and package it with git-annex
- pull these two "new" BIDS dataset for training your model (with ivadomed you can now aggregate two separate BIDS datasets)

**Comment by mariehbourget** [comment]
@rezazad68, I checked the config file and the problem is with the suffix in "contrast_params". 
`T2w_mid` is not accepted by BIDS, it should be only `T2w` (in the config file AND in the filenames)

We have an opened issue (#707) about the Prepare_dataset_vertebral_labeling script that does not produce bids compliant files. I updated the issue this morning with the proposed solution from Julien which is to create a separate "processed" dataset and drop the `mid `in the filename.

**Comment by rezazad68** [comment]
@mariehbourget I have revised the code to generate the rec-mid files but still did not solve the issue. I have attached screenshots for your reference. 

![am1](https://user-images.githubusercontent.com/20574689/116620231-d5cecb80-a941-11eb-8318-8fbd775c791e.png)
![am2](https://user-images.githubusercontent.com/20574689/116620234-d6676200-a941-11eb-912f-b1a7bf39ddbb.png)
![am3_config](https://user-images.githubusercontent.com/20574689/116620236-d6fff880-a941-11eb-898e-edfd1f39747e.png)

**Comment by mariehbourget** [comment]
Thanks for the screenshots :)

3 things:
1) In the derivatives, the `heatmap0` suffix should be at the end or the file name (ex: `sub-amu01_rec-mid_T1w_heatmap0.nii.gz`)
2) In the config file: `contrast_params` should be only `T1w`.
3) The current loader will not make the difference between `sub-amu01_rec-mid_T1w.nii.gz` and `sub-amu01_T1w.nii.gz` at the moment. We plan on adding filters for that in the future (#708). In the meantime, the proposed solution is to create a new BIDS  dataset with only the preproceesed files (only the `rec-mid` files that you need for training)

**Comment by rezazad68** [comment]
Thanks fixed :)
