### ISSUE TITLE
Affine matrix error in Cascaded architecture tutorial

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#775]
## Issue description

I got an error while running the tutorial [Cascaded architecture](https://ivadomed.org/en/latest/tutorials/cascaded_architecture.html#cascaded-architecture).
It seems to be related to the affine matrix in Nibabel objects that is used to generate bounding boxes.

### Current behavior
While following the steps of the tutorial, I have the following error message during training.

<details>
<summary> Error message </summary>

```
Traceback (most recent call last):
  File "/home/mhbourget/venv-ivadomed-38c/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 548, in run_main
    run_command(context=context,
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 368, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 117, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/mhbourget/ivadomed/ivadomed/loader/loader.py", line 99, in load_dataset
    dataset = BidsDataset(bids_df=bids_df,
  File "/home/mhbourget/ivadomed/ivadomed/loader/loader.py", line 1127, in __init__
    bounding_box_dict = imed_obj_detect.load_bounding_boxes(object_detection_params,
  File "/home/mhbourget/ivadomed/ivadomed/object_detection/utils.py", line 248, in load_bounding_boxes
    bounding_box_dict = generate_bounding_box_file(subject_path_list,
  File "/home/mhbourget/ivadomed/ivadomed/object_detection/utils.py", line 122, in generate_bounding_box_file
    ras_orientation = nib.as_closest_canonical(object_mask)
  File "/home/mhbourget/venv-ivadomed-38c/lib/python3.8/site-packages/nibabel/funcs.py", line 205, in as_closest_canonical
    img = img.as_reoriented(io_orientation(img.affine))
  File "/home/mhbourget/venv-ivadomed-38c/lib/python3.8/site-packages/nibabel/orientations.py", line 55, in io_orientation
    q, p = affine.shape[0] - 1, affine.shape[1] - 1
IndexError: tuple index out of range
```
</details>

I'm not very familiar with the "bounding box" feature but from my understanding:
1. in `generate_bounding_box_file`, a new segmentation is generated with `segment_volume` [here](https://github.com/ivadomed/ivadomed/blob/5579c71e8c93dfdb0ca72952bdde604b84bc645e/ivadomed/object_detection/utils.py#L114)
2. then `segment_volume` creates the Nibabel object with `pred_to_nib` [here](https://github.com/ivadomed/ivadomed/blob/5579c71e8c93dfdb0ca72952bdde604b84bc645e/ivadomed/inference.py#L296)
3. in `pred_to_nib `[here](https://github.com/ivadomed/ivadomed/blob/5579c71e8c93dfdb0ca72952bdde604b84bc645e/ivadomed/inference.py#L92), the header of the reference file is copied in the new object, but not the affine matrix
4. then in `generate_bounding_box_file` [here](https://github.com/ivadomed/ivadomed/blob/5579c71e8c93dfdb0ca72952bdde604b84bc645e/ivadomed/object_detection/utils.py#L122), the Nibabel function `as_closest_canonical` tries to read the affine metadata in the Nibabel object (which is `None`).

It may be related to a previous PR (#714)  where it was decided to copy the header of Nibabel objects instead of the affine matrix.

### Questions

I would need a second opinion on this from someone with more experience with the feature and to make sure I'm not doing anything wrong on my side.
If the error persists, should we copy both the affine matrix and the header when creating output prediction in `pred_to_nib`?
ex:
```
    nib_pred = nib.Nifti1Image(
        dataobj=arr_pred_ref_space,
        affine=nib_ref.affine,      ## Instead of affine=None
        header=nib_ref.header.copy()
    )
```

### Related PR
The draft PR (#758) also deals with copy of header instead of affine matrix when creating Nibabel objects.

**Comment by charleygros** [comment]
@jcohenadad may have an idea about this nibabel tricky creature?

**Comment by joshuacwnewton** [comment]
I don't have experience with this specific feature, but lately I've been diving more into nibabel with SCT (specifically with header-related issues). I'm also interested in learning more about ivadomed. So, I can take a look at this tomorrow. :)

**Comment by joshuacwnewton** [comment]
> If the error persists, should we copy both the affine matrix and the header when creating output prediction in `pred_to_nib`?
> ex:
> 
> ```
>     nib_pred = nib.Nifti1Image(
>         dataobj=arr_pred_ref_space,
>         affine=nib_ref.affine,      ## Instead of affine=None
>         header=nib_ref.header.copy()
>     )
> ```

Also, just as a very quick surface-level observation, the header itself contains an affine matrix. In other words, if the header is copied, then it shouldn't be necessary to also copy the affine matrix.

<details> 
<summary> Technical nitpicky details </summary>

---

The header _technically_ doesn't contain an affine matrix. It contains fields which are then used to construct 3 different matrices: the sform affine ([info here](https://nipy.org/nibabel/nifti_images.html#the-sform-affine)), the qform affine ([info here](https://nipy.org/nibabel/nifti_images.html#the-qform-affine)), and the fallback affine ([info here](https://nipy.org/nibabel/nifti_images.html#the-fall-back-header-affine)). Nibabel [uses an algorithm](https://nipy.org/nibabel/nifti_images.html#choosing-image-affine) to decide which one of the 3 should be used as "the affine matrix".
</details>

**Comment by jcohenadad** [comment]
> So, my hunch is that the root cause isn't because affine=None.

that's also my gut feeling-- it is possible that at prior steps, the input image has inconsistent header and/or the affine matrix of the header is "lost in translation"...

**Comment by joshuacwnewton** [comment]
I followed the tutorial and I am able to reproduce the error.

<details>
<summary> Full output log </summary>

```
❯ git checkout -b jn/775-cascaded-tutorial-affine-error
Switched to a new branch 'jn/775-cascaded-tutorial-affine-error'
❯ ivadomed_download_data -d data_example_spinegeneric

ivadomed (git-jn/775-cascaded-tutorial-affine-error-5579c71e8c93dfdb0ca72952bdde604b84bc645e)

Trying URL: https://github.com/ivadomed/data_example_spinegeneric/archive/r20200825.zip
Downloading: data_example_spinegeneric-r20200825.zip
Unzip data to: /tmp/tmp87ou3lnm
Removing temporary folders...
Folder Created: /home/joshua/repos/ivadomed/data_example_spinegeneric
❯ cp ivadomed/config/config.json .
❯ gedit config.json
❯ ivadomed -c config.json -t 0.01 -g 1
Adding the following keys to the configuration file
    loader_parameters: is_input_dropout: False
    default_model: is_2d: True


Output path already exists: spineGeneric
Cuda is not available.
Working on cpu.

Selected architecture: Unet, with the following parameters:
        dropout_rate: 0.3
        bn_momentum: 0.1
        depth: 3
        is_2d: True
        final_activation: sigmoid
        folder_name: my_model
        in_channel: 1
        out_channel: 1
Dataframe has been saved in spineGeneric/bids_dataframe.csv.
After splitting: train, validation and test fractions are respectively 0.6, 0.2 and 0.2 of participant_id.

Selected transformations for the ['training'] dataset:
        Resample: {'wspace': 0.75, 'hspace': 0.75, 'dspace': 1}
        CenterCrop: {'size': [64, 64]}
        RandomAffine: {'degrees': 5, 'scale': [0.1, 0.1], 'translate': [0.03, 0.03], 'applied_to': ['im', 'gt']}
        ElasticTransform: {'alpha_range': [28.0, 30.0], 'sigma_range': [3.5, 4.5], 'p': 0.1, 'applied_to': ['im', 'gt']}
        NumpyToTensor: {}
        NormalizeInstance: {'applied_to': ['im']}

Selected transformations for the ['validation'] dataset:
        Resample: {'wspace': 0.75, 'hspace': 0.75, 'dspace': 1}
        CenterCrop: {'size': [64, 64]}
        NumpyToTensor: {}
        NormalizeInstance: {'applied_to': ['im']}

WARNING: fname_roi has not been specified, then the entire volume is processed.

Loaded 16 axial slices.
Traceback (most recent call last):
  File "/home/joshua/repos/ivadomed/venv/bin/ivadomed", line 33, in <module>
    sys.exit(load_entry_point('ivadomed', 'console_scripts', 'ivadomed')())
  File "/home/joshua/repos/ivadomed/ivadomed/main.py", line 548, in run_main
    run_command(context=context,
  File "/home/joshua/repos/ivadomed/ivadomed/main.py", line 368, in run_command
    ds_valid = get_dataset(bids_df, loader_params, valid_lst, transform_valid_params, cuda_available, device,
  File "/home/joshua/repos/ivadomed/ivadomed/main.py", line 117, in get_dataset
    ds = imed_loader.load_dataset(bids_df, **{**loader_params, **{'data_list': data_lst,
  File "/home/joshua/repos/ivadomed/ivadomed/loader/loader.py", line 99, in load_dataset
    dataset = BidsDataset(bids_df=bids_df,
  File "/home/joshua/repos/ivadomed/ivadomed/loader/loader.py", line 1030, in __init__
    bounding_box_dict = imed_obj_detect.load_bounding_boxes(object_detection_params,
  File "/home/joshua/repos/ivadomed/ivadomed/object_detection/utils.py", line 248, in load_bounding_boxes
    bounding_box_dict = generate_bounding_box_file(subject_path_list,
  File "/home/joshua/repos/ivadomed/ivadomed/object_detection/utils.py", line 122, in generate_bounding_box_file
    ras_orientation = nib.as_closest_canonical(object_mask)
  File "/home/joshua/repos/ivadomed/venv/lib/python3.8/site-packages/nibabel/funcs.py", line 205, in as_closest_canonical
    img = img.as_reoriented(io_orientation(img.affine))
  File "/home/joshua/repos/ivadomed/venv/lib/python3.8/site-packages/nibabel/orientations.py", line 55, in io_orientation
    q, p = affine.shape[0] - 1, affine.shape[1] - 1
IndexError: tuple index out of range
```
</details>

<details>
<summary> config.json, modified as per tutorial </summary>

```json
{
    "command": "train",
    "gpu_ids": [0],
    "path_output": "spineGeneric",
    "model_name": "my_model",
    "debugging": true,
    "object_detection_params": {
        "object_detection_path": "data_example_spinegeneric/trained_model/seg_sc_t1-t2-t2s-mt",
        "safety_factor": [2.0, 2.0, 1.0]
    },
    "loader_parameters": {
        "path_data": ["data_example_spinegeneric"],
        "subject_selection": {"n": [], "metadata": [], "value": []},
        "target_suffix": ["_csfseg-manual"],
        "extensions": [".nii.gz"],
        "roi_params": {
            "suffix": null,
            "slice_filter_roi": null
        },
        "contrast_params": {
            "training_validation": ["T2w"],
            "testing": ["T2w"],
            "balance": {}
        },
        "slice_filter_params": {
            "filter_empty_mask": false,
            "filter_empty_input": true
        },
        "slice_axis": "axial",
        "multichannel": false,
        "soft_gt": false
    },
    "split_dataset": {
        "fname_split": null,
        "random_seed": 6,
        "split_method" : "participant_id",
        "data_testing": {"data_type": null, "data_value":[]},
        "balance": null,
        "train_fraction": 0.6,
        "test_fraction": 0.2
    },
    "training_parameters": {
        "batch_size": 18,
        "loss": {
            "name": "DiceLoss"
        },
        "training_time": {
            "num_epochs": 100,
            "early_stopping_patience": 50,
            "early_stopping_epsilon": 0.001
        },
        "scheduler": {
            "initial_lr": 0.001,
            "lr_scheduler": {
                "name": "CosineAnnealingLR",
                "base_lr": 1e-5,
                "max_lr": 1e-2
            }
        },
        "balance_samples": {
            "applied": false,
            "type": "gt"
        },
        "mixup_alpha": null,
        "transfer_learning": {
            "retrain_model": null,
            "retrain_fraction": 1.0,
            "reset": true
        }
    },
    "default_model": {
        "name": "Unet",
        "dropout_rate": 0.3,
        "bn_momentum": 0.1,
        "final_activation": "sigmoid",
        "depth": 3
    },
    "FiLMedUnet": {
        "applied": false,
        "metadata": "contrasts",
        "film_layers": [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    },
    "Modified3DUNet": {
        "applied": false,
        "length_3D": [128, 128, 16],
        "stride_3D": [128, 128, 16],
        "attention": false,
        "n_filters": 8
    },
    "uncertainty": {
        "epistemic": false,
        "aleatoric": false,
        "n_it": 0
    },
    "postprocessing": {
        "remove_noise": {"thr": -1},
        "keep_largest": {},
        "binarize_prediction": {"thr": 0.5},
        "uncertainty": {"thr": -1, "suffix": "_unc-vox.nii.gz"},
        "fill_holes": {},
        "remove_small": {"unit": "vox", "thr": 3}
    },
    "evaluation_parameters": {
        "target_size": {"unit": "vox", "thr": [20, 100]},
        "overlap": {"unit": "vox", "thr": 3}
    },
    "transformation": {
        "Resample":
        {
            "wspace": 0.75,
            "hspace": 0.75,
            "dspace": 1
        },
        "CenterCrop": {
            "size": [64, 64]},
        "RandomAffine": {
            "degrees": 5,
            "scale": [0.1, 0.1],
            "translate": [0.03, 0.03],
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
        "ElasticTransform": {
			"alpha_range": [28.0, 30.0],
			"sigma_range":  [3.5, 4.5],
			"p": 0.1,
            "applied_to": ["im", "gt"],
            "dataset_type": ["training"]
        },
      "NumpyToTensor": {},
      "NormalizeInstance": {"applied_to": ["im"]}
    }
}
```
</details>

**Comment by joshuacwnewton** [comment]
Everything that @mariehbourget was correct: the `affine` object is `None`, and this does in fact matter here. 

The nibabel function `as_closest_canonical` [accesses `img.affine` directly](https://github.com/nipy/nibabel/blob/62aea04248e70d7c4529954ca41685d7f75a0b1e/nibabel/funcs.py#L205), rather than using `img.header.get_best_affine`. So, what I said earlier about the header affine doesn't apply here. (Sorry about that!)

WIll keep digging...

**Comment by joshuacwnewton** [comment]
> If the error persists, should we copy both the affine matrix and the header when creating output prediction in pred_to_nib?

I've asked about this upstream (see linked issue above) to get some clarification on whether we should copying the header, or if we should instead be specifying `affine`.

**Comment by joshuacwnewton** [comment]
> If the error persists, should we copy both the affine matrix and the header when creating output prediction in pred_to_nib?

@mariehbourget Your proposed solution matches up with what was suggested here: https://github.com/nipy/nibabel/issues/1012#issuecomment-831980457 :tada:

**Comment by jcohenadad** [comment]
just to keep in mind: we should be careful, if we decide on specifying the affine, to not reintroduce the issue addressed in https://github.com/ivadomed/ivadomed/pull/714

**Comment by joshuacwnewton** [comment]
> just to keep in mind: we should be careful, if we decide on specifying the affine, to not reintroduce the issue addressed in #714

Thanks for pointing this out. You're absolutely right to be cautious: Reading the docs on [`Nifti1Image`](https://nipy.org/nibabel/reference/nibabel.nifti1.html#nibabel.nifti1.Nifti1Image), it says:

> If both a header and an affine are specified, and the affine does not match the affine that is in the header, the affine will be used, but the sform_code and qform_code fields in the header will be re-initialised to their default values. This is performed on the basis that, if you are changing the affine, you are likely to be changing the space to which the affine is pointing. The set_sform() and set_qform() methods can be used to update the codes after an image has been created - see those methods, and the manual for more details.

So, I think we might be better off explicitly setting sform/qform as part of this change, as instructed above.

**Comment by dyt811** [comment]
Hmm...  have yet to dig into the entire Cascaded architecture tutorial in depth, but would this be address by the fix Hanna has been implemented on PR#758 to address Issue#715 which was raised after PR#714 address part of the prediction file header problem?

**Comment by joshuacwnewton** [comment]
> Hmm... have yet to dig into the entire Cascaded architecture tutorial in depth, but would this be address by the fix Hanna has been implemented on #758 to address #715 which was raised after #714 address part of the prediction file header problem?

Unfortunately, #758 contains the same issue described here (setting `affine=None` and relying on just `header`). So, it also needs to be amended using whichever solution is settled on here.

**Comment by jcohenadad** [comment]
i suggest we try `Nifti1Image(data, img.header.get_best_affine(), img.header.copy())` and see if #714 does not come back

**Comment by copperwiring** [comment]
Thank you for working on this issue. This issue has one of the function calls `pred_to_nib` ([here](https://github.com/ivadomed/ivadomed/blob/5579c71e8c93dfdb0ca72952bdde604b84bc645e/ivadomed/inference.py#L92)) mentioned but for completion I'd like to add that in addition to the modification in `inference.py/pred_to_nib`, the same fix (whateevr is agreed upon) must be applied in `inference.py/split_classes`  ([here](https://github.com/ivadomed/ivadomed/blob/20e0346f4132013dc466d9637633abb7093750ca/ivadomed/inference.py#L478)) as discussed [here](https://github.com/ivadomed/ivadomed/issues/921).
