### ISSUE TITLE
Contribution Guide in the Wiki

### ISSUE THREAD

**Issue by ssinad** [ivadomed/ivadomed#798]
## Issue description
The file linked in the wiki points to a symbolic link instead of an actual file.

### Current behavior

This is what is currently shown.
```
../../CONTRIBUTING.rst
```

### Expected behavior
 
The contents of [CONTRIBUTING.rst](https://github.com/ivadomed/ivadomed/blob/master/CONTRIBUTING.rst)

### Installed packages

<details open>
<summary> Output of <code>pip freeze</code> </summary>

```

```

</details>

**Comment by jcohenadad** [comment]
@ssinad reason for closing?

**Comment by ssinad** [comment]
I fixed the link on the wiki to point to the original file instead of the symbolic link.

**Comment by jcohenadad** [comment]
great thx-- in the future pls always document the reason for closing an issue

**Comment by ssinad** [comment]
For sure.
