### ISSUE TITLE
Accommodate training of very big datasets

### ISSUE THREAD

**Issue by mpompolas** [ivadomed/ivadomed#799]
## This issue is placed in order to start a discussion about the potential options.

The datasets that we have in our disposal are only getting bigger.

We should slowly start thinking how we can speed up the loading process, since right now the loader is loading everything before the computations get started leading to very long waiting times.

We should probably consider partial loading in extreme cases and/or modifications to the loader based on the available RAM

**Comment by dyt811** [comment]
So my limited understanding is that PyTorch Dataset/DataLoader can readily handle multi terabyte of training data without issue. But because  we are preloading some of the 2d/3d volumes data for various reasons into Bids3DDataset/BidsDataset objects before training time which even though those classes inherit from Dataset/DataLoader and will train okay by only loading bulk of the training relevant data at training time, we are potentially going to see CPU RAM overflow before training at BIDS object formation stage, and not GPU RAM overflow during mini-batch training, is that correct?

**Comment by charleygros** [comment]
Hi @maffos, Thanks for your message!

> From my understanding all crops of the dataset are loaded into main-memory before training

Yes, correct!

> Have you considered any workaround?

We have been discussing to implement solutions to address this issue, things around "training on the fly". But nothing really started at this stage.

> Otherwise I would try modifying the code such that the images are only actually loaded within the getitem function of the dataloader.

That would be really great! I do like the idea you suggested!
Please feel free to create a "Draft" Pull Request so that the `ivadomed` team can support you with the integration of the changes etc.

**Comment by jcohenadad** [comment]
related to #773

**Comment by dyt811** [comment]
@naga-karthik good point. I was hoping @entiri would be able to look into this a bit more post parallel training PR fix but ran into quite a bit road block getting metrics back for his parallel training. Let's talk about a bit more now that I have Compute Canada access and should be able to test larger data loading in conjunction with the latest singularity fixes.

**Comment by uzaymacar** [comment]
As per the ivadomed meeting today, I investigated how we do things currently vs. what MONAI does. Following up on @mpompolas's suggestion, here is what I came up with:
 
<img width="999" alt="Screen Shot 2022-04-12 at 12 59 45 AM" src="https://user-images.githubusercontent.com/33473983/162840489-f263345c-3ef8-4741-ab2e-b548a87a9a26.png">

To briefly summarize:
* In both MONAI and ivadomed, non-deterministic data augmentations are applied in the `__get_item()` function of the corresponding dataset classes, i.e. on the fly during training.
* As discussed in this thread, ivadomed pre-computes all preprocessing steps and slicing in the `__init__()` function of our dataset classes. The preprocessed data is cached in the `self.handlers` list. See the [_load_filenames()](https://github.com/ivadomed/ivadomed/blob/7b76bf81a025cde3096fd1d686d6f3c0b8ce8f02/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py#L54) and [_prepare_indices()](https://github.com/ivadomed/ivadomed/blob/7b76bf81a025cde3096fd1d686d6f3c0b8ce8f02/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py#L80) helper functions for this.
* MONAI implements a [`CacheDataset()`](https://github.com/Project-MONAI/MONAI/blob/af6560a5facef14483e43cb516d8f07d72aa1ffe/monai/data/dataset.py#L150) class which is analogous to how we do things in ivadomed. It also implements a [`PersistentDataset()`](https://github.com/Project-MONAI/MONAI/blob/af6560a5facef14483e43cb516d8f07d72aa1ffe/monai/data/dataset.py#L619) class that saves the preprocessed data to a directory to be read later as opposed to storing it on RAM. **This helps handle accommodate large datasets** and is analogous to @jcohenadad's suggestion in the previous ivadomed meeting.
* Besides the standard implementations, MONAI includes more niche methods for caching and persistency which I am yet to explore further. Among them is [Smart Cache](https://docs.nvidia.com/clara/tlt-mi_archive/clara-train-sdk-v3.0/nvmidl/additional_features/smart_cache.html) from NVIDIA which "determines the most effective data to cache based on the determinism of transforms". This method mitigates the issue of exploding RAM for caching methods as it uses a configurable cache capacity (i.e. store as much as you can in RAM w/o exploding). This is similar to @mpompolas's suggestion IIRC. 

I think a nice next step would be to add a key to our dataset classes that reflects the pre-computation strategy with options `persistent` and `cache` (default in ivadomed). `persistent` can be implemented by saving the contents of the `self.handlers` list to directory, removing the contents from memory, and re-reading the contents during `__get_item()`. Another topic of discussion for the near-future would be to see if we can integrate MONAI's dataset classes as well (in parallel to the models effort in #1116).
