### ISSUE TITLE
Verify intended behavior or test_segment_volume_2d with ROI

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#802]
## Issue description
In `funtional_tests/test_segment_volume.py`, I think `test_segment_volume_2d` was intended to test the segmentation with a ROI because of the use of `ROI_PATH` in the `segment_volume`.

### Current behavior
The `ROI_PATH` param passed to the command in the test [here](https://github.com/ivadomed/ivadomed/blob/05dbd217cc9b4c06a0bef77ce06cc57937dd45ec/testing/functional_tests/test_segment_volume.py#L73) is not assigned to the `options` argument, and end up in the third argument `gpu_id` instead.

So, the segmentation test works, but it doesn't test with the ROI, as confirmed by the terminal output:
`WARNING: fname_roi has not been specified, then the entire volume is processed. `

The test would also fail on GPU because of the wrong `gpu_id`.

In addition, in order for the test to use the ROI, a `suffix` ("_seg-manual") should be specified in `roi_params` of the the `loader parameters`, otherwise the `ROICrop` transform will do a crop around the center of the image instead of a crop around the ROI.

### Expected behavior
I could take care of the PR to fix this but I would need someone to confirm if the test should or should not test with ROI, @andreanne-lemay, @charleygros?
Thanks!

**Comment by dyt811** [comment]
I noticed that too during Cascade tutorial and was wondering where the warning message came from and why the ROI volume from the tutorial was not really applied it seems and I wasn't sure if I was doing the tutorial wrong. I think you just helped me there.

**Comment by charleygros** [comment]
> I could take care of the PR to fix this but I would need someone to confirm if the test should or should not test with ROI, @andreanne-lemay, @charleygros?

I agree with you @mariehbourget ! Every single word and comma!
