### ISSUE TITLE
segment_volume issues after refactoring

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#803]
## Issue description

While working on #782, I encountered a two issues with the `segment_volume` function since the refactoring in #791 (tagging @dyt811 so he is aware). The issues described below are present on `master` branch.

#### 1) local variable 'model' referenced before assignment
In the call for `get_preds` [here](https://github.com/ivadomed/ivadomed/blob/05dbd217cc9b4c06a0bef77ce06cc57937dd45ec/ivadomed/inference.py#L358), the argument `model` is not defined when the model in a onnx model.
<details>
<summary> Error </summary>

```
File "/home/mhbourget/ivadomed/ivadomed/inference.py", line 361, in segment_volume
preds = get_preds(context, model, fname_model, model_params, cuda_available, batch)
UnboundLocalError: local variable 'model' referenced before assignment
```
</details>

#### 2) last_sample_bool, weight_matrix and volume are re-initialized at each iteration
`reconstruct_3d_object` is in a the "batch" for loop  [here](https://github.com/ivadomed/ivadomed/blob/05dbd217cc9b4c06a0bef77ce06cc57937dd45ec/ivadomed/inference.py#L366). `last_sample_bool, weight_matrix, volume` are initialized in `reconstruct_3d_object` [here](https://github.com/ivadomed/ivadomed/blob/05dbd217cc9b4c06a0bef77ce06cc57937dd45ec/ivadomed/inference.py#L409), whereas they were initialized outside of the for loop before. They are used to reconstruct a 3D volume from several sub-volumes and should not be re-initialized at each batch iteration. This result in the following error, because volume is None at the second iteration and should not be.
<details>
<summary> Error </summary>

```
File "/home/mhbourget/ivadomed/ivadomed/inference.py", line 479, in volume_reconstruction
volume[:, x_min:x_max, y_min:y_max, z_min:z_max] += pred[smp_idx]
TypeError: 'NoneType' object is not subscriptable
```
</details>

From my understanding, `last_sample_bool, weight_matrix, volume` should be initialized before the for loop, they should be passed in arguments to `reconstruct_3d_object` and also return by the function.

### Expected behavior and test
I found this because I used the exact same principle in my PR #782 to reconstruct images from 2d patches and it does not work anymore because of the re-initialization of `last_sample_bool, weight_matrix, volume`. I confirmed that the issue is on my branch with 2D patches as well as on `master` branch with 3D sub-volumes. We should fix this issue on `master` first before I go on with PR.

We have a test for the second issue: `test_segment_volume_3d` in `functional_tests/test_segment_volume.py`.

The test did not catch the error because the `CenterCrop` transform (size of the volume being segmented) is the same as the `length_3D` of the `Modified3DUNet` model (size of 1 sub-volume). Because of that, there is only 1 sub-volume in the full volume, hence the for loop does only 1 iteration and the issue is not caught.

To test properly, we should change the `CenterCrop` parameter of this test from `[96, 96, 16]` to `[192, 192, 16]`, which would give us 4 sub-volume of `[96, 96, 16]` to reconstruct the full volume of `[192, 192, 16]`.

### Steps to reproduce

- I tested on `master` branch.
- I trained a dummy 3D model for a few epochs on the `data_example_spinegeneric` dataset with the `config_tumorSeg.json` file, changing the `length_3D` and `stride_3D` parameters of `Modified3DUnet` by `[256, 128, 16]` (for an entire volume i.e. `CenterCrop` of `[512, 256, 16]`) (there may be an already trained 3D model somewhere to test this @andreanne-lemay, @charleygros?)
- I switched the command to `segment` in the config file, segment uses `segment_volume` and the segmentation fails with the errors describe above.
- Note: the same model with the command `test` works, because `test` does not use the `segment_volume` function.

**Comment by dyt811** [comment]
I encountered the first Model not found error as well while testing Cascade tutorial. That has been patched in my WIP branch at [here](https://github.com/ivadomed/ivadomed/tree/yd/803-hotpatch_segment_volume). I have managed to make I believe is the change @mariehbourget recommended and updated the test accordingly but I believe it is still failing the updated test. Not sure if @mariehbourget have any suggestions there? I am going to get a draft PR going.

**Comment by dyt811** [comment]
> From my understanding, last_sample_bool, weight_matrix, volume should be initialized before the for loop, they should be passed in arguments to reconstruct_3d_object and also return by the function.

So in the PR803 I have just pulled those instantiations out of the loop but I am still getting the same type of error in the new unit test (with `[192. 192. 16]` , mostly around `volume` variable with is None and during subsequent batch volume remains `None`. 

Since `volume` and `weight_matrix` are tensors class, they are past by references in Python so it should not be required to return/assign after each iterative call to `reconstruct_3d_object()`. In the PR I added the return assignment on [line 388 ](https://github.com/ivadomed/ivadomed/blob/yd/803-hotpatch_segment_volume/ivadomed/inference.py#L377)for the boolean since that is not past by reference. 

Any comment or insight greatly appreciated.

**Comment by dyt811** [comment]
PR #804 has just been updated to incorporated the fix @mariehbourget recommended and the additional unit test scenario. Huge kudos to coming up with the recommended fix so soon as it would have taken me a long time to discover this by myself. 

Anyone who can review and approve and merge ASAP as this is an important bug to patch ASAP.
