### ISSUE TITLE
Tests failing but CI checks reported as successfull

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#810]
## Issue description
I'm working on PR #782. My PR is not completed and the tests `test_segment_volume_2d` and `test_segment_volume_2d_with_patches` on github are failing at the moment (which is normal).

However, the checks from the new Github Action CI on multi-platform are reported as successfull, even though they are not. 
Example in `Run tests on all platforms / Matrix Test of Python 3.6 on macos-latest (pull_request)`:
```
=========================== short test summary info ============================
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d_with_patches[center_crop0]
FAILED testing/functional_tests/test_segment_volume.py::test_segment_volume_2d_with_patches[center_crop1]
=========== 3 failed, 196 passed, 370 warnings in 495.46s (0:08:15) ============
```
Also, the check `Matrix Test of Python 3.8 on macos-11` seems to be stuck.

Tagging @dyt811 so he is aware.

**Comment by dyt811** [comment]
Hey ,@mariehbourget, could you try the following: 

1. Rerun the failing CI tests and see if they all passes as before. 
2. IF they do, could you change [this line](https://github.com/ivadomed/ivadomed/blob/master/.github/workflows/run_tests.yml#L33) in your PR branch to remove the `{0}` and see if that helps detecting error?

**Comment by ssinad** [comment]
I think `{0}` is the issue.
Removing it caused the tests to fail [here](https://github.com/ssinad/ivadomed/runs/2695759497).

**Comment by dyt811** [comment]
Yeah, I think that line forces all runs to not stop and keep going until very end and return 0. It was suppose to help force all tests to run to keep going and get more data out of each run and return all output but in this case, it is too dangerous. I will get a PR going to fix it. Could you approve it ASAP when I ping you on slack?

**Comment by mariehbourget** [comment]
> Hey ,@mariehbourget, could you try the following:
> 
> 1. Rerun the failing CI tests and see if they all passes as before.
> 2. IF they do, could you change [this line](https://github.com/ivadomed/ivadomed/blob/master/.github/workflows/run_tests.yml#L33) in your PR branch to remove the `{0}` and see if that helps detecting error?

I started the checks again but if I understand correclty, they will pass again.
I'll wait for your PR instead of changing the {0} as Sina has already tested it.

What about he `Matrix Test of Python 3.8 on macos-11` stuck test? (`Expected — Waiting for status to be reported`)

**Comment by dyt811** [comment]
> What about he `Matrix Test of Python 3.8 on macos-11` stuck test? (`Expected — Waiting for status to be reported`)

Yeah, I don't have admin function to trigger if that is required but that one needs to be removed as it is blocking all PRs.
