### ISSUE TITLE
Segment command fails with multiple raters

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#816]
## Issue description
While working on PR #806, I found a bug with the multiple raters feature with the command `segment`.

### Current behavior
When running the `segment` command, the output filename contains the` target_suffix` of the config file saved with the model, ex: `originalName_targetSuffix_pred.nii.gz`. It fails with the following error, because for each class, the `target_suffix` is a list and not a string.
```
Traceback (most recent call last):
  File "/home/mhbourget/venv-ivadomed-38c/bin/ivadomed", line 11, in <module>
    load_entry_point('ivadomed', 'console_scripts', 'ivadomed')()
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 555, in run_main
    run_command(context=context,
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 335, in run_command
    run_segment_command(context, model_params)
  File "/home/mhbourget/ivadomed/ivadomed/main.py", line 278, in run_segment_command
    filename = subject.split('.')[0] + target + "_pred" + \
TypeError: can only concatenate str (not "list") to str
```

### Steps to reproduce
1. Train a model with multiple raters (PR #806 must be merged first)
2. Segment images with the same model with the `segment` command

**Comment by charleygros** [comment]
Thanks @mariehbourget!

Additional info: The aim of the fonction [check_multiple_raters ](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/main.py#L89 )was originally to avoid this kind of error. To fix this issue, I'd recommend to start with looking at it!
