### ISSUE TITLE
test_sampler.py failing unexpectedly

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#825]
## Issue description

I merged PR #813 this morning and `test_sampler.py` is failing after the merge on master in one of the CI configuration (`Matrix Test of Python 3.6 on ubuntu-18.04`) [here](https://github.com/ivadomed/ivadomed/runs/2821454340). The test was passing on my branch previous to the merge.

Looking back at previous merges and PRs, it seems that this test is failing often and in different configurations, recent examples [here](https://github.com/ivadomed/ivadomed/runs/2768334110) in `Matrix Test of Python 3.6 on ubuntu-20.04` and [here](https://github.com/ivadomed/ivadomed/runs/2644886231) in `test (3.7, integration-test)`. I'm not familiar with the feature but there may be an bug with it or with the test itself that makes it fail unexpectedly.

**Comment by dyt811** [comment]
So it seems the underlying process is probabilitic: 
![image](https://user-images.githubusercontent.com/6720068/123362624-f92b8680-d53e-11eb-8d0f-ef37f5b58d79.png)
![image](https://user-images.githubusercontent.com/6720068/123362654-05174880-d53f-11eb-9322-628c54266ffa.png)
![image](https://user-images.githubusercontent.com/6720068/123362691-13656480-d53f-11eb-9a2e-2aee6d42f101.png)

but the assertion ensures that unbalanced results will randomly become more balanced eventually but in some odd CI state, it did not. Best to run this issue many times locally and see what is up with that. 

![image](https://user-images.githubusercontent.com/6720068/123362891-6b03d000-d53f-11eb-90fd-57739cd36e08.png)

**Comment by jcohenadad** [comment]
good digging @dyt811 !

**Comment by cakester** [comment]
the only difference between the two runs of this test is that one uses random sampler:
 ```   
def __iter__(self):
        n = len(self.data_source)
        if self.replacement: #False
            return iter(torch.randint(high=n, size=(self.num_samples,), dtype=torch.int64).tolist())
        return iter(torch.randperm(n).tolist())
```
the other one uses balanced multinomial sampler:
```
    def __iter__(self):
        return (self.indices[i] for i in torch.multinomial(
            self.weights, self.nb_samples, replacement=True))
```
and if they happen to generate the same numbers we have an error such as above, (if you replace the second __iter__ with torch.randperm(n).tolist() such as above you get the same error), suggest change < to <=

**Comment by dyt811** [comment]
@cakester good catch. 

Glad the fix wasn't super involved. Going to run a 3000+ retry to ensure it stays that way before approving the PR and we can wrap this up. 

BTW `@pytest.mark.repeat(1000)`  from `pytest-repeat` is PRETTY cool for this.
