### ISSUE TITLE
Installation instruction steps explicity recommended for MacOS but not Linux

### ISSUE THREAD

**Issue by copperwiring** [ivadomed/ivadomed#839]
The installation instructions on Ivadomed (https://ivadomed.org/en/latest/installation.html) mention:

> Currently, we only support MacOS and Linux operating systems. Windows users have the possibility to install and use ivadomed via Windows Subsystem for Linux (WSL).For MacOs users, we strongly recommend to follow the bellow steps before the installation.

As a new user this was a little confusing because it gave me an impression that detailed Linux instructions are elsewere (or after MacOS). Is there a particular reason to mention this strong recommendation for MacOS. Are there alternatives of linux?

**Suggestion:**
Since the first line already mentions `we only support MacOS and Linux operating systems`, we can do **one** of the folllowing:

1. Remove `For MacOs users, we strongly recommend to follow the bellow steps before the installation.`  OR
2.  Add an additional line saying something for linux to avoid confusion.

**Comment by dyt811** [comment]
Good spot. That red section below was specifically added back then to address a MacOS specific issue. 

![image](https://user-images.githubusercontent.com/6720068/124413076-ed4d7a80-dd1d-11eb-92bc-b8cc8896182c.png)

The related PR is #771  and issue #633 and #768 and how if that environmental variable is not set on macOS, some functions related hd5 file reading/writing test will fail. However, this was not an issue in Linux/Ubuntu/Windows for some reason.

**Comment by copperwiring** [comment]
Thank you for your clarification @dyt811. I looked at the PRs and issues and this seems an important step. I would recommend something like:

> The steps below are strongly recommended for MacOS users in the installation and optional for Linux users.

or we remove the MacOS thing and simply let it be:

> We strongly recommend to follow the bellow steps before the installation.

Would like to know your opinion @konantian .

**Comment by konantian** [comment]
@copperwiring thanks for tagging me. I totally agree with this. The current instruction is a little confusing for both MacOS and Linux users and we definitely need to update that. I would recommend modifying the instruction in the first way.

**Comment by copperwiring** [comment]
Thank you @konantian. Appreciate your response. I will send a PR for this and will then close this issue.
