### ISSUE TITLE
New `torch` instructions will make it harder for downstream packages to depend on ivadomed's Python API

### ISSUE THREAD

**Issue by joshuacwnewton** [ivadomed/ivadomed#861]
In #757, `ivadomed` stopped listing `torch`+`torchvision` as default dependencies, instead opting to ask users to choose between the GPU/CPU versions and [install them themselves](https://ivadomed.org/en/latest/installation.html#step-3-install-pytorch-1-5-and-torchvision). But, I think this change might make it harder for any downstream packages to depend on `ivadomed`:

*  If another Python package lists `ivadomed` in their package requirements (e.g. via `setup.py` -> `install_requires=`), then `ivadomed` will be broken out of the box (since `torch` is missing).
* The [replacement instructions](https://ivadomed.org/en/latest/installation.html#approach-2-venv) aren't really possible for a downstream package to follow (because another package's `setup.py` can't clone a repository to install `torch` via `requirements_gpu.txt`/`requirements.txt`).
* So, a downstream package will have to list `torch` as one of their dependencies _on behalf_ of `ivadomed`. 
    * This is what [`spinalcordtoolbox` is currently doing](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/0bef2991f0c05251fbf43df8d1fc0360960565c2/requirements.txt#L28-L36), which is easy enough for us, because SCT's development has been somewhat intertwined with ivadomed's development.
    * But, this might discourage other packages from using ivadomed's Python API, since it might not be clear which functionalities are accessible and which aren't.

**Comment by mathieuboudreau** [comment]
Hi from AxonDeepSeg 👋

I was been debugging for like an hour right now my ADS installation using IVADOMED as a (new) requirements, wondering why it was throwing me a missing torch package error when I was loading IVADOMED in python.

I'd assume you guys had included it in your setup, if it was a requirement to run IVADOMED.

So... yeah, +1 for this issue getting resolved. I saw no instructions before I had the idea to search "requirements" in your issues and found this.

**Comment by mathieuboudreau** [comment]
(I know I was being a bad user by not reading your README thoroughly, sorry about that. But... not every user will 🤷)

**Comment by mathieuboudreau** [comment]
> (I know I was being a bad user by not reading your ReadTheDocs thoroughly, sorry about that. But... not every user will 🤷)

ALTHOUGH...... in my defence.....

I just noticed that your ReadTheDocs button links to your stable release: https://ivadomed.org/en/stable/?badge=stable

...which is missing the instructions to install torch that you linked in this issue, which is from the latest release: https://ivadomed.org/en/latest/installation.html#approach-2-venv

...so it's not *really* my fault I missed it 🙃

I'll open an issue for that one.

**Comment by dyt811** [comment]
I think maybe we can try to implement this: https://discuss.pytorch.org/t/how-to-add-pytorch-as-a-requirement-in-setup-py/106188, namely a parsing function for setup.py so we can streamline the `torch` installation process because right now, the installation instructions is branching out like overgrown potatoes...
