### ISSUE TITLE
ReadTheDocs button on README points to "stable", which is out of date from "latest"

### ISSUE THREAD

**Issue by mathieuboudreau** [ivadomed/ivadomed#871]
See this thread: https://github.com/ivadomed/ivadomed/issues/861#issuecomment-885959088

The button links here: https://ivadomed.org/en/stable/?badge=stable

But that release of the docs doesn't include the latest instructions to install `torch`, which is in the latest branch here: https://ivadomed.org/en/latest/installation.html#approach-2-venv

**Comment by mathieuboudreau** [comment]
Reflecting on this a bit more, I'm guessing maybe your RTD might be pointing to stable because you only want to give docs by default for the releases and on the development versions? If that's the case and is a conscious one, my bad, I'm just used to some other repos having docs up-to-date with the master branch.

**Comment by jcohenadad** [comment]
Hum, by default, ivadomed points to _latest_, not _stable_:
![image](https://user-images.githubusercontent.com/2482071/127060388-0d99dab3-f95d-4c95-a338-c0c10565f2d3.png)

Now, it is possible that _latest_ is the latest release, not master, in which case we might want to change that and make "latest" be master instead. Feedback welcome.

**Comment by mathieuboudreau** [comment]
Ahh, @jcohenadad I didn't mean the ivadomed website ([ivadomed.org](http://www.ivadomed.org)), but the `docs|passing` badge/button on the README file of this repository, here:

<img width="899" alt="Screen Shot 2021-07-26 at 9 11 26 PM" src="https://user-images.githubusercontent.com/1421029/127074961-f3667ae5-d6d2-4888-816d-c9bee1a44e4c.png">

due to this line:

https://github.com/ivadomed/ivadomed/blob/7a595ae39e94085837582f7176b8ec59bd9a2bc9/README.md#L8

where `stable` is hardcoded in.
