### ISSUE TITLE
Resample axis inverted in documentation

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#908]
## Issue description

In the RTD documentation of Resample [here](https://ivadomed.org/en/latest/configuration_file.html#resample), the resampling spaces are described as:
`wspace`: Resolution along the **first** axis, in mm.
`hspace`: Resolution along the **second** axis, in mm.
`dspace`: Resolution along the **third** axis, in mm.

In reality in the code [here](https://github.com/ivadomed/ivadomed/blob/cc020c2c78d37ee1f34bda35bf24b6f8fc73114e/ivadomed/transforms.py#L274), the resampling spaces are applied as:
`hspace`: Resolution along the **first** axis, in mm.
`wspace`: Resolution along the **second** axis, in mm.
`dspace`: Resolution along the **third** axis, in mm.

If I'm not mistaken, the docstrings and behavior of the `Resample` function are correct but the `hspace` and `wspace` axis are inverted in the documentation.

**Comment by copperwiring** [comment]
@charleygros Can you confirm that it is RTD here that is wrong and it should be:

```
hspace: Resolution along the **first** axis, in mm.
wspace: Resolution along the **second** axis, in mm.
```

**Comment by charleygros** [comment]
> 
> 
> @charleygros Can you confirm that it is RTD here that is wrong and it should be:
> 
> ```
> hspace: Resolution along the **first** axis, in mm.
> wspace: Resolution along the **second** axis, in mm.
> ```

Yep I confirm.
That's a bit more complex than this tho, eg hspace is the first axis in mm AFTER reorientation to the canonical orientation then slice extraction. See canonical [here ](https://github.com/ivadomed/ivadomed/blob/e8398e5651f859680bebc4dffb6ca465660987b5/ivadomed/loader/utils.py#L559) for instance.

For instance, if the input nifti is SAR (Sagital - Anterior - Right) and the slice extraction orientation is axial --> it will be first reoriented to RAS then RA slices extracted along the SI (Superior to Inferior) axis. So the hspace will be along the RL (Right to Left axis).

Hope it helps.
