### ISSUE TITLE
Wrong output in training_curve.py

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#915]
## Issue description

I’m testing the [training_curve.py](https://ivadomed.org/en/latest/scripts.html#ivadomed-training-curve) script and found an odd behavior. The script output a plot for each metrics from tensorboard event files. However, some plots don’t have the “right” content in them.

### Current behavior
For example, on rosenberg (master branch commit 93b9e73):
- `hausdorff_score.png` contains the tensorboard curve of `specificity`
- `intersection_over_union.png` contains the tensorboard curve of `precision`
- `precision_score.png` contains the tensorboard curve of `hausdorff`
- `specificity_score.png` contains the tensorboard curve of `intersection_over_union`

I also tried on my laptop and got different “bad” pairings (master branch commit 93b9e73):
- `accuracy_score.png` contains the tensorboard curve of `specificity`
- `dice_score.png` contains the tensorboard curve of `accuracy`
- `intersection_over_union.png` contains the tensorboard curve of `recall`
- `recall_score.png` contains the tensorboard curve of `dice`
- `precision_score.png` contains the tensorboard curve of `intersection_over_union`
- `specificity_score.png` contains the tensorboard curve of `precision`

### Steps to reproduce
- I’m using this command to plot curves from 2 models:
`ivadomed_training_curve -i path_output_model1,path_output_model2 -o path_output_for_png`
- Then I compre the png outputs with the tensorboard display.

Note: I have the same issue when using only one model path in `-i`.

**Comment by charleygros** [comment]
Mmmm interesting :-(

As it is related to metrics only, the issue probably comes from somewhere in [this loop](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/training_curve.py#L182) ?

**Comment by mariehbourget** [comment]
> As it is related to metrics only, the issue probably comes from somewhere in [this loop](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/scripts/training_curve.py#L182) ?

@charleygros, I tested it a bit further, the error is not in the loop directly but in the order of the `events_df_list` used to loop, this list comes from [tensorboard_retrieve_event](https://github.com/ivadomed/ivadomed/blob/c28c49e965e4b9644e178ca349e41fffdc559ea6/ivadomed/scripts/training_curve.py#L196).

- In `tensorboard_retrieve_event`, the code [here](https://github.com/ivadomed/ivadomed/blob/c28c49e965e4b9644e178ca349e41fffdc559ea6/ivadomed/scripts/training_curve.py#L207) expects the metrics to be in a specific (hardcoded) order: `dice, multiclass dice, hausdorff, precision, recall, specificity, intersection_over_union, accuracy`.
- The order above is supposed to correspond to the order that they are written in training, buy it doesn't match. Order in training [here](https://github.com/ivadomed/ivadomed/blob/c28c49e965e4b9644e178ca349e41fffdc559ea6/ivadomed/metrics.py#L9) is: `dice, multi_class_dice, precision, recall, specificity, intersection_over_union, accuracy, hausdorff`.
- Moreover, regardless of the order in training, it seems that the events files are read in the order of `os.listdir` [here](https://github.com/ivadomed/ivadomed/blob/c28c49e965e4b9644e178ca349e41fffdc559ea6/ivadomed/scripts/training_curve.py#L215). (funny story: it is now `iterdir` with `Pathlib`, PR #886 was merged during my debugging).
- The `os.listdir` output is not always in the same order which explains the difference in behavior that I had between my laptop and rosenberg. For each machine, the mismatch between metrics corresponds to the difference between the expected hardcoded list vs. the order of `os.listdir` (and had nothing to do with the order written in training).

I'll re-test it now with Pathlib and try to fix the issue.

**Comment by dyt811** [comment]
Just wanna say, that is some good investigative work. 👍 TIL. Thanks for sharing.
