### ISSUE TITLE
Wrong key for dropout in config file

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#926]
## Issue description
The dropout key in configuration file does not correspond to the expected key in models' definitions.

### Current behavior
In config files (including `config_default.json`) and in the documentation, the key for dropout in the model parameter is `dropout_rate`. This key is passed to the model in training in `model_params` here: https://github.com/ivadomed/ivadomed/blob/bc1b543fd3df448a18b8ed87f99f18ca19af2fe7/ivadomed/training.py#L100
However, all models are expecting the key to be `drop_rate`.
Ex:ample here in Unet model: https://github.com/ivadomed/ivadomed/blob/bc1b543fd3df448a18b8ed87f99f18ca19af2fe7/ivadomed/models.py#L489
So `dropout_rate` from the config is never used and the default `drop_rate` of each model applies.

### Expected behavior
For the models to use the correct dropout from the config files.
I see 3 options for fixing it.

**Option 1:**
- Update all the config files in `ivadomed/config` with the key `drop_rate` instead of `dropout_rate`.
- Update the documentation accordingly.

**Option 2:**
- Update all the config files in `ivadomed/config` with the key `drop_rate` instead of `dropout_rate` (same as option 1).
- Update the documentation accordingly (same as option 1).
- Make a key change in `config_manager.py` to change `dropout_rate` to `drop_rate`, so both are supported.

**Option 3:**
- Change the key in all models' definitions to `dropout_rate`.

I'm more in favor of option 1 for retrocompatibility purposes i.e. old training with the wrong key will remain the same and still be wrong if the training is run again.
Option 2 and 3 would change the behavior of old config files.

Let me know what you think.

**Comment by charleygros** [comment]
... shame

**Comment by charleygros** [comment]
Marie-Helene Bourget, aka Oeil de Lynx :-)

Anyway.. in other words: good catch and thank you!

I do like Option 1 too, but `drop_rate` is not very intuitive.. I do prefer `dropout_rate`.

```
 Option 2 and 3 would change the behavior of old config files.
```

I understand for Option 3, but not sure for Option 2: Why would Option 2 change the behavior of old config files? Can you help me with this one?

**Comment by mariehbourget** [comment]
> I understand for Option 3, but not sure for Option 2: Why would Option 2 change the behavior of old config files? Can you help me with this one?

In Option 2, `dropout_rate` would be changed to `drop_rate` by the config manager, similar to previous keys that changed (ex: `log_directory --> path_output` here: https://github.com/ivadomed/ivadomed/blob/959b54d7f0094479b64182a7a386978d0147618e/ivadomed/config_manager.py#L69-L93
In this scenario, both `drop_rate` and `dropout_rate` would end up in the `drop_rate` argument of the models. So an "old" model where the `dropout_rate` was NOT applied (because of the wrong key), would now be applied.

**Comment by mariehbourget** [comment]
As discussed in meeting, I'll fix the issue with Option 3 as we prefer to keep only 1 key, `dropout_rate` is a better name than `drop_rate`, and retrocompatibility of old config files is not an issue.
