### ISSUE TITLE
final_activation value not checked for validity

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#927]
## Issue description
According to the [documentation](https://ivadomed.org/en/latest/configuration_file.html#default-model), the `final_activation` key of model parameters in config files accepts 3 values: `softmax`, `relu` or `sigmoid`. With `sigmoid` being the default if the key is not present. However, there are no mechanism to catch a wrong value for that key.

### Current behavior
If the key is not present, `sigmoid` is used as expected.
If the value  `softmax`, `relu` or `sigmoid` are spelled correctly, the right `final_activation` is used as expected.

However, if the key is present in the config file but the value is not one of the three above (ex: `"final_activation": "asdf"`), `sigmoid` is used without warning or error in the else block in the Unet Decoder here: https://github.com/ivadomed/ivadomed/blob/bc1b543fd3df448a18b8ed87f99f18ca19af2fe7/ivadomed/models.py#L441-L455

Same goes for Modified3DUnet here: https://github.com/ivadomed/ivadomed/blob/bc1b543fd3df448a18b8ed87f99f18ca19af2fe7/ivadomed/models.py#L1109-L1115

### Expected behavior
The code should check the key and raise an error if the value is not valid.

**Comment by dyt811** [comment]
Great eye. Also another place to take out magical strings. @cakester will be able to take a look. 

Thank you for the EXCELLENT problem description.  A+ 😆
