### ISSUE TITLE
`_tkinter.TclError` for `test_dice_plot` on Py3.7/windows-latest CI job

### ISSUE THREAD

**Issue by joshuacwnewton** [ivadomed/ivadomed#930]
I noticed a failing test for the newest commit on master (https://github.com/ivadomed/ivadomed/commit/69d3a3443a534c9e49239f3ae96ddf23531df9a4), as well as my branch which I recently merged master into (https://github.com/ivadomed/ivadomed/pull/852). 

The error log for master can be found here: https://github.com/ivadomed/ivadomed/pull/852/checks?check_run_id=3487015049#step:7:224

```python
 >       self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: Can't find a usable init.tcl in the following directories: 
E           {C:\hostedtoolcache\windows\Python\3.7.9\x64\tcl\tcl8.6}
E       
E       C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl: couldn't read file "C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl": No error
E       couldn't read file "C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl": No error
E           while executing
E       "source C:/hostedtoolcache/windows/Python/3.7.9/x64/tcl/tcl8.6/init.tcl"
E           ("uplevel" body line 1)
E           invoked from within
E       "uplevel #0 [list source $tclfile]"
E       
E       
E       This probably means that Tcl wasn't installed properly.
```

The same test passed on [@dyt811's branch](https://github.com/ivadomed/ivadomed/runs/3480188522?check_suite_focus=true), though. I was curious, so I diffed the install logs (https://www.diffchecker.com/HuiHb5g1), and didn't see any upstream changes that would have caused this.

* Searching GitHub, a similar issue was reported in https://github.com/alteryx/evalml/issues/2580, and they're reporting it as intermittent... :thinking: 
* A few other reports mention needing to set `TCL_LIBRARY` environment variable... 
    * https://github.com/touilleMan/godot-python/issues/303
    * https://github.com/ihaveamac/custom-install/issues/52
* I currently don't have a good explanation apart from that. :sweat_smile:

**Comment by dyt811** [comment]
I reran that job and prayed to the Random Number Generator $DIETY. Let's see how reproducible this is...

**Comment by joshuacwnewton** [comment]
Indeed! Looks good to me: https://github.com/ivadomed/ivadomed/runs/3487015020
