### ISSUE TITLE
Trained model incorrect/missing for uncertainty estimation tutorial 

### ISSUE THREAD

**Issue by copperwiring** [ivadomed/ivadomed#938]
From tutorial [here](https://ivadomed.org/en/latest/tutorials/uncertainty.html), the trained model is expected to be in this path:

```
"path_output": "<PATH_TO_DATASET>/data_example_spinegeneric/trained_model"
```
and the name of the model expected is: 

`trained_moded.pt` in the folder 

`<PATH_TO_DATASET>/data_example_spinegeneric/trained_model`

as seen [here](https://github.com/ivadomed/ivadomed/blob/d71a1c4711d03da7c61a473f571134b262684073/ivadomed/models.py#L1489). However, no such mode exists in the path as seen below:

![image](https://user-images.githubusercontent.com/23316280/131910166-02ebf526-7335-417d-ae5d-dfc367cae7cb.png)

The model that does exist is `best_model.pt`. So either the model provided is provided with incorrect name or the model is missing altogether.

**Comment by charleygros** [comment]
Ok I get it now :-)

So the trained model is here:
```
(base) chgroc@rosenberg:~$ ls master_ivadomed/ivadomed/data_example_spinegeneric/trained_model/seg_sc_t1-t2-t2s-mt/
seg_sc_t1-t2-t2s-mt.json  seg_sc_t1-t2-t2s-mt.onnx
```
--> both the model (onnx format) and the related config file

So the following lines in the tutorial are correct:
```
path_output: Location of the directory containing the trained model. To avoid having to train a model from scratch, in the downloaded dataset, there is a trained model for spinal cord segmentation in the folder trained_model. Modify the path so it points to the location of the trained model.

"path_output": "<PATH_TO_DATASET>/data_example_spinegeneric/trained_model"
```

However the folder name is not very intuitive for a `path_output`.
Options include ask the user to do a `cp trained_model XX` with XX something more intuitive, (this option is herebelow called OPTION_CP).

The `model_name` in the config file should be `seg_sc_t1-t2-t2s-mt` tho (not `trained_model`).

This [section](https://ivadomed.org/en/latest/tutorials/uncertainty.html#run-uncertainty-estimation) contains multiple errors:
- `path_data` should point towards `data_example_spinegeneric`
- `path_output` points towards `<PATH_TO_DATASET>/data_example_spinegeneric/trained_model` or OPTION_CP.

Another comment about this tutorial: we are asking the user to modify the config file... but after we are inviting them to use the CLI.. then we say Oh well you dont have to do this if you modify the CLI --> I find it a bit confusing tbh.

Hope it helps :-)
