### ISSUE TITLE
Wrong instruction for sct_run_batch

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/ivadomed#948]
full context: https://forum.spinalcordmri.org/t/segmentation-mask/741/16?u=jcohenadad

An SCT user arrived at the [`dev/prepare_data`](https://github.com/ivadomed/ivadomed/tree/master/dev/prepare_data) section, and noticed that the instructions are out of date. The usage in the [README.md](https://github.com/ivadomed/ivadomed/blob/master/dev/prepare_data/README.md) needs to be updated from the old `parameters.sh` format to SCT's new `config.yml` format.

**Comment by joshuacwnewton** [comment]
When I was working on the SCT Course documentation, I ran into the same outdated syntax there too. (Previously, the SCT course mentioned `parameters.sh` -> I reworked the tutorial to use the newer `.yml` format.)

Since I'm already familiar with it, I would be happy to update the documentation for ivadomed as well.

**Comment by joshuacwnewton** [comment]
@jcohenadad By the by, do you have any idea how an SCT user ended up at these internal ivadomed dev scripts? i.e. Were they directed to that folder at some point, or did they discover it on their own?

**Comment by jcohenadad** [comment]
> When I was working on the SCT Course documentation, I ran into the same outdated syntax there too. (Previously, the SCT course mentioned `parameters.sh` -> I reworked the tutorial to use the newer `.yml` format.)
> 
> Since I'm already familiar with the necessary changes, I would be happy to update the documentation for ivadomed as well.

That would be amazing! thank you so much!

> (Though, I think it would be worth considering avoiding hardcoding SCT instructions in ivadomed documentation at all. Since, being separate from the SCT repo, it is much more likely to fall out of date.)

Agreed. On the other hand being 100% verbose about how an experiment was run (instead of redirecting to SCT's doc) promotes reproducibility of the results. But of course, in that case, we need to put a large disclaimer like "THIS WAS TESTED ON SCT vX.X".

> I'm realizing now that these are meant to be "internal" scripts and not publicly exposed to users.
> 
> Side question: @jcohenadad Do you happen to know how one of our users ended up at these internal ivadomed dev scripts? i.e. Were they directed to that folder at some point, or did they discover it on their own?

On their own, I think.
