### ISSUE TITLE
Apply `slice_filter_params` on 2D patches 

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#979]
### Motivation for the feature
In the `loader parameters`, we have a [slice_filter_params](slice_filter_params
) to filter out empty input, empty mask or absent class.
The filters are applied [here](https://github.com/ivadomed/ivadomed/blob/2e5f70faa67e2a21f9ae11ada69145256aa6629b/ivadomed/loader/mri2d_segmentation_dataset.py#L109) on the entire image.
For microscopy, we would like to be able to filter on each patch of an image.

### Description of the feature
To filter on the "patch" level, we would need to apply the filters in [prepare_indices](https://github.com/ivadomed/ivadomed/blob/2e5f70faa67e2a21f9ae11ada69145256aa6629b/ivadomed/loader/mri2d_segmentation_dataset.py#L135), where the coordinates for the patches of the dataset are indexed.

**Comment by jcohenadad** [comment]
thank you @mariehbourget-- just to clarify, by "filter", here we mean "remove" (per opposition as e.g. apply a Gaussian filter)
