### ISSUE TITLE
Issue with configuration file documentation build

### ISSUE THREAD

**Issue by mariehbourget** [ivadomed/ivadomed#991]
## Issue description
Something seems to be wrong with the current build of the [Configuration file documentation page](https://ivadomed.org/configuration_file.html), it shows only the examples and not the explanations of each of the parameters.

It currently looks like this (after the merge of PR #989):
![image](https://user-images.githubusercontent.com/54086142/141827265-f8474e65-ffee-438d-8dd0-976332c3e88f.png)

It should be (from the previous merge of PR #988)
![image](https://user-images.githubusercontent.com/54086142/141827648-8fd96815-a1a2-4da6-96e4-1a9f343dfbf0.png)

tagging @dyt811

**Comment by dyt811** [comment]
Odd. Just checked the page, it seems fine. I wonder if it is just a random build failure? Current page seems fine? 

I wonder if subsequent PR merge resulted in the proper build and if this is a release PR specific issue?

**Comment by mariehbourget** [comment]
Odd indeed!

I'm in Chrome on Windows 10.
The problematic build was from PR #989 here: https://ivado-medical-imaging--989.org.readthedocs.build/configuration_file.html, it is still not showing OK for me.

However the latest build (current doc page) is fine!
Thank you for following-up, looks like a random build failure.

**Comment by dyt811** [comment]
Yeah, super odd. I wonder if this is a Release PR specific problem? Post subsequent PR merge, we no longer see this at `ivadomed.org`. So we should keep an eye out to check for the configuration page after each PR to see if this re-emerge, especially next release PR just in case. Thanks for reporting this.
